import { useEffect,useRef,useState } from 'react'
type V={size:string;sku:string;openingStock:number}
export default function AddProduct({onDone}:{onDone:()=>void}){
 const skuRequest=useRef(0)
 const [name,setName]=useState(''),[code,setCode]=useState(''),[category,setCategory]=useState(''),[cost,setCost]=useState(0),[sale,setSale]=useState(0),[rows,setRows]=useState<V[]>([{size:'',sku:'',openingStock:0}]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{if(!name.trim()||code)return;const t=setTimeout(()=>fetch('/api/products/suggest-code?name='+encodeURIComponent(name)).then(r=>r.json()).then(j=>setCode(j.productCode||'')),250);return()=>clearTimeout(t)},[name])
 async function suggest(i:number,size:string){setRows(current=>current.map((v,x)=>x===i?{...v,size}:v));if(!code||!size)return;const request=++skuRequest.current;try{const r=await fetch('/api/products/suggest-sku?productCode='+encodeURIComponent(code)+'&size='+encodeURIComponent(size));const j=await r.json();if(request!==skuRequest.current||!r.ok)return;setRows(current=>current.map((v,x)=>x===i&&v.size===size?{...v,sku:j.sku||''}:v))}catch{}}
 async function save(){if(busy)return;setBusy(true);setMsg('');try{const r=await fetch('/api/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,productCode:code,category,costPrice:cost,salePrice:sale,variants:rows})});const j=await r.json();if(!r.ok)return setMsg(j.error||'Không thể tạo sản phẩm');setMsg('Đã tạo sản phẩm.');onDone()}catch(e){setMsg(e instanceof Error?e.message:'Không thể tạo sản phẩm')}finally{setBusy(false)}}
 return <div className="approval"><h3>Tạo sản phẩm thủ công</h3><div className="formGrid"><label>Tên<input value={name} onChange={e=>{setName(e.target.value);setCode('')}}/></label><label>Mã sản phẩm<input value={code} onChange={e=>setCode(e.target.value)}/></label><label>Danh mục<input value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Giá nhập<input type="number" min="0" value={cost} onChange={e=>setCost(Number(e.target.value)||0)}/></label><label>Giá bán<input type="number" min="0" value={sale} onChange={e=>setSale(Number(e.target.value)||0)}/></label></div><h4>Size / SKU / tồn đầu</h4>{rows.map((v,i)=><div className="variantEdit" key={i}><input placeholder="Size" value={v.size} onChange={e=>void suggest(i,e.target.value)}/><input placeholder="SKU" value={v.sku} onChange={e=>{const n=[...rows];n[i]={...n[i],sku:e.target.value};setRows(n)}}/><input type="number" min="0" step="1" value={v.openingStock} onChange={e=>{const n=[...rows];n[i]={...n[i],openingStock:Math.max(0,Math.trunc(Number(e.target.value)||0))};setRows(n)}}/><button disabled={rows.length===1} onClick={()=>setRows(rows.filter((_,x)=>x!==i))}>XÓA</button></div>)}<div className="inventoryActions"><button onClick={()=>setRows([...rows,{size:'',sku:'',openingStock:0}])}>+ THÊM SIZE</button><button className="primary" disabled={busy} onClick={save}>{busy?'ĐANG LƯU...':'LƯU SẢN PHẨM'}</button></div>{msg&&<p className="notice">{msg}</p>}</div>
}
