import { useEffect, useMemo, useState } from 'react'
import InventoryOps from './InventoryOps'
import AddProduct from './AddProduct'
import InventoryView from './InventoryView'
import SettingsView from './SettingsView'
import GoodsReceipt from './GoodsReceipt'
import ProductDetail from './ProductDetail'

type Health={ok:boolean;version:string;schema:number;database:string}
type ScanSize={size:string;images:string[];suggestedSku:string;existingVariantId?:number;costPrice?:number;salePrice?:number;status?:'NEW'|'EXISTING'}
type ScanProduct={name:string;suggestedProductCode:string;existingProductId?:number;status?:'NEW'|'EXISTING'|'PARTIAL';sizes:ScanSize[];warnings:string[]}
type ScanResult={mode:string;rootPath:string;productCount:number;products:ScanProduct[]}
type DraftSize=ScanSize&{openingStock:number;sku:string;costPrice:number;salePrice:number;selected:boolean}
type DraftProduct={name:string;productCode:string;category:string;costPrice:number;salePrice:number;variants:DraftSize[]}
type ProductRow={id:number;product_code:string;name:string;category?:string;variant_count:number;total_stock:number;image_id?:number|null}
const demo:ProductRow[]=[
{id:1,product_code:'LG0001',name:'Lửng gái T5',category:'Đồ tole bé gái',variant_count:3,total_stock:12},
{id:2,product_code:'BG0001',name:'Bộ gái hoa',category:'Đồ tole bé gái',variant_count:4,total_stock:7}
]
const nav=['Tổng quan','Danh mục sản phẩm','Nhập hàng','Import kho','Tồn kho','Cài đặt']

export default function App(){
 const isDemo=useMemo(()=>location.hostname.endsWith('github.io'),[])
 const [health,setHealth]=useState<Health|null>(null),[active,setActive]=useState('Tổng quan')
 const [menuOpen,setMenuOpen]=useState(false),[menuSearch,setMenuSearch]=useState(''),[darkMode,setDarkMode]=useState(false)
 const [products,setProducts]=useState<ProductRow[]>(isDemo?demo:[]),[search,setSearch]=useState('')
 const [root,setRoot]=useState(''),[scan,setScan]=useState<ScanResult|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 const [draft,setDraft]=useState<DraftProduct|null>(null)
 const [batchSelected,setBatchSelected]=useState<Record<number,boolean>>({}),[batchProgress,setBatchProgress]=useState('')
 const [opsProductId,setOpsProductId]=useState<number|null>(null)
 const [showAdd,setShowAdd]=useState(false),[productReload,setProductReload]=useState(0)
 const [detailProductId,setDetailProductId]=useState<number|null>(null),[dashboard,setDashboard]=useState<any>(null),[catalog,setCatalog]=useState<any>(null)
 useEffect(()=>{if(isDemo)return;fetch('/api/health').then(r=>r.json()).then(setHealth).catch(()=>setHealth(null))},[isDemo])
 useEffect(()=>{if(isDemo||active!=='Tổng quan')return;fetch('/api/inventory/dashboard').then(r=>r.json()).then(setDashboard).catch(()=>setDashboard(null))},[active,isDemo,productReload])
 useEffect(()=>{if(isDemo)return;if(active==='Danh mục sản phẩm'){fetch('/api/products?search='+encodeURIComponent(search)).then(r=>r.json()).then(setProducts).catch(()=>setProducts([]));fetch('/api/catalog/dashboard').then(r=>r.json()).then(setCatalog).catch(()=>setCatalog(null))}},[active,search,isDemo,productReload])
 const mode=isDemo?'DEMO':health?.ok?'LOCAL':'LOCAL / API OFFLINE'
 async function doScan(){if(isDemo){setMsg('DEMO chỉ xem giao diện; quét folder chỉ chạy ở LOCAL.');return}setBusy(true);setMsg('');try{const r=await fetch('/api/store/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rootPath:root})});const j=await r.json();if(!r.ok)throw new Error(j.error);setScan(j);setBatchSelected(Object.fromEntries((j.products??[]).map((_:ScanProduct,i:number)=>[i,true])))}catch(e){setMsg(e instanceof Error?e.message:'Không thể quét kho')}finally{setBusy(false)}}
 function editProduct(p:ScanProduct){setDraft({name:p.name,productCode:p.suggestedProductCode,category:'',costPrice:0,salePrice:0,variants:p.sizes.map(s=>({...s,sku:s.suggestedSku,openingStock:s.status==='EXISTING'?0:s.images.length,costPrice:s.costPrice??0,salePrice:s.salePrice??0,selected:s.status!=='EXISTING'}))});setMsg('')}
 function updateVariant(i:number,key:'size'|'sku'|'openingStock'|'costPrice'|'salePrice',value:string){if(!draft)return;const variants=[...draft.variants];variants[i]={...variants[i],[key]:key==='openingStock'?Math.max(0,Math.trunc(Number(value)||0)):key==='costPrice'||key==='salePrice'?Math.max(0,Number(value)||0):value};setDraft({...draft,variants})}
 async function commitBatch(){
  if(!scan||isDemo||busy)return
  const selected=scan.products.map((p,i)=>({p,i})).filter(x=>batchSelected[x.i])
  if(!selected.length){setMsg('Chưa chọn sản phẩm để lưu.');return}
  setBusy(true);setMsg('');let ok=0
  try{
   for(const {p} of selected){
    const variants=p.sizes.filter(s=>s.status!=='EXISTING').map(s=>({size:s.size,sku:s.suggestedSku,openingStock:s.images.length,costPrice:s.costPrice??0,salePrice:s.salePrice??0,images:s.images}))
    if(!variants.length){ok++;setBatchProgress(ok+'/'+selected.length);continue}
    const payload={confirmed:true,product:{rootPath:scan.rootPath,name:p.name,productCode:p.suggestedProductCode,category:'',costPrice:0,salePrice:0,variants}}
    const r=await fetch('/api/store/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json()
    if(!r.ok)throw new Error(p.name+': '+(j.error||'Import thất bại'))
    ok++;setBatchProgress(ok+'/'+selected.length)
   }
   setMsg('Đã xử lý '+ok+' sản phẩm. Quét lại để đối chiếu trạng thái mới.');await doScan()
  }catch(e){setMsg('Đã lưu '+ok+'/'+selected.length+'. Dừng tại lỗi: '+(e instanceof Error?e.message:'Import thất bại'))}
  finally{setBusy(false);setBatchProgress('')}
 }
 async function commitDraft(){if(!draft||!scan)return;if(isDemo){setMsg('DEMO không ghi dữ liệu.');return}setBusy(true);setMsg('');try{const payload={confirmed:true,product:{rootPath:scan.rootPath,name:draft.name,productCode:draft.productCode,category:draft.category,costPrice:draft.costPrice,salePrice:draft.salePrice,variants:draft.variants.filter(v=>v.selected).map(v=>({size:v.size,sku:v.sku,openingStock:v.openingStock,costPrice:v.costPrice,salePrice:v.salePrice,images:v.images}))}};const r=await fetch('/api/store/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error);setMsg('Đã import sản phẩm thành công.');setDraft(null);setScan(null)}catch(e){setMsg(e instanceof Error?e.message:'Import thất bại')}finally{setBusy(false)}}
 const menuItems=nav.filter(n=>n.toLocaleLowerCase('vi').includes(menuSearch.trim().toLocaleLowerCase('vi')))
 function goTo(section:string){setActive(section);setMenuOpen(false);setMenuSearch('');setDetailProductId(null)}
 return <div className={'shell '+(darkMode?'themeDark':'')}>
  <header className="topbar"><div className="brandIdentity"><button type="button" className="menuToggle" aria-label="Mở danh mục chức năng" aria-expanded={menuOpen} onClick={()=>setMenuOpen(true)}>☰</button><img className="brandLogo" src={`${import.meta.env.BASE_URL}brand/logo.jpg`} alt="Logo Shop Mẹ CaCao" onError={e=>{e.currentTarget.style.display="none"}}/><span className="brandMonogram">MC</span><div><p className="eyebrow">SHOP MẸ CACAO · SINCE 2023</p><h1>Quản lý kho</h1></div></div><div className="headerActions"><button type="button" className="themeToggle" onClick={()=>setDarkMode(v=>!v)} aria-label={darkMode?"Bật giao diện sáng":"Bật giao diện tối"}>{darkMode?"☀":"☾"}</button><span className={'badge '+(mode==='LOCAL'?'local':mode==='DEMO'?'demo':'offline')}>{mode}</span></div></header>
  {menuOpen&&<div className="drawerBackdrop" onClick={()=>setMenuOpen(false)}><aside className="featureDrawer" role="dialog" aria-modal="true" aria-label="Danh mục chức năng" onClick={e=>e.stopPropagation()}><div className="drawerHead"><img src={`${import.meta.env.BASE_URL}brand/logo.jpg`} alt="" /><div><b>Shop Mẹ CaCao</b><small>Danh mục chức năng</small></div><button type="button" aria-label="Đóng danh mục" onClick={()=>setMenuOpen(false)}>×</button></div><div className="drawerSearch"><span>⌕</span><input autoFocus value={menuSearch} onChange={e=>setMenuSearch(e.target.value)} placeholder="Tìm chức năng..." /></div><p className="drawerSection">QUẢN LÝ CỬA HÀNG · {menuItems.length} CHỨC NĂNG</p><div className="drawerLinks">{menuItems.map((n,i)=><button type="button" key={n} className={active===n?"selected":""} onClick={()=>goTo(n)}><span className="drawerIcon">{({ "Tổng quan":"⌂","Danh mục sản phẩm":"▦","Nhập hàng":"＋","Import kho":"⇩","Tồn kho":"▤","Cài đặt":"⚙"} as Record<string,string>)[n]}</span><span>{n}</span><span className="drawerArrow">›</span></button>)}{menuItems.length===0&&<p>Không tìm thấy chức năng phù hợp.</p>}</div><div className="drawerFoot"><span className="drawerDot"/> {mode} · Since 2023</div></aside></div>}
  <div className="layout"><nav className="sidebar">{nav.map(n=><button key={n} className={active===n?'active':''} onClick={()=>setActive(n)}><strong>{n}</strong></button>)}</nav>
  <main><section className="hero"><img className="brandBanner" src={`${import.meta.env.BASE_URL}brand/banner.jpg`} alt="Banner Shop Mẹ CaCao" onError={e=>{e.currentTarget.style.display="none"}}/><p className="eyebrow">SHOP MẸ CACAO · SINCE 2023</p><h2>{active}</h2><p>Quản lý sản phẩm, size và hàng tồn trực quan. Dữ liệu thực tế chỉ hoạt động trên máy LOCAL.</p></section>
  {active==='Tổng quan'&&<><section className="grid dashboardGrid"><article className="card"><span>TỔNG TỒN</span><strong>{isDemo?'19':dashboard?.stock??'—'}</strong><p>bộ theo ảnh kho thực tế</p></article><article className="card"><span>SẢN PHẨM</span><strong>{isDemo?'2':dashboard?.products??'—'}</strong><p>mẫu đang quản lý</p></article><article className="card"><span>SKU / SIZE</span><strong>{isDemo?'7':dashboard?.skus??'—'}</strong><p>biến thể đang quản lý</p></article><article className="card"><span>SẮP HẾT</span><strong>{isDemo?'1':dashboard?.lowProducts?.length??'—'}</strong><p>còn ≤ {2}</p></article><article className="card"><span>HẾT HÀNG</span><strong>{isDemo?'0':dashboard?.outOfStock??'—'}</strong><p>Size chưa có ảnh hàng</p></article></section>{!isDemo&&dashboard?.attention?.length>0&&<section className="panel"><h3>Cần chú ý</h3><div className="detailTable">{dashboard.attention.map((x:any)=><div key={x.variant_id}><div><b>{x.product_name}</b><small>{x.product_code} · {x.size} · {x.sku}</small></div><strong>{x.stock} tồn</strong></div>)}</div></section>}</>}
  {active==='Nhập hàng'&&(isDemo?<section className="panel"><h3>Nhập hàng</h3><p>DEMO chỉ xem. Copy ảnh và ghi tồn chỉ chạy LOCAL.</p></section>:<GoodsReceipt/>)}
  {active==='Tồn kho'&&(isDemo?<section className="panel"><h3>Tồn kho</h3><p>DEMO chỉ xem giao diện. Dữ liệu tồn thật chỉ hoạt động ở LOCAL.</p></section>:<InventoryView/>)}
  {active==='Cài đặt'&&(isDemo?<section className="panel"><h3>Cài đặt & Backup</h3><p>DEMO không ghi cài đặt hoặc tạo backup. Các chức năng này chỉ hoạt động ở LOCAL.</p></section>:<SettingsView/>)}
  {active==='Danh mục sản phẩm'&&<><section className="catalogMetrics"><article><span>MẪU SẢN PHẨM</span><strong>{isDemo?2:catalog?.products??'—'}</strong></article><article><span>SIZE / SKU</span><strong>{isDemo?7:catalog?.skus??'—'}</strong></article><article><span>DANH MỤC</span><strong>{isDemo?1:catalog?.categories??'—'}</strong></article><article><span>SIZE THIẾU ẢNH</span><strong>{isDemo?0:catalog?.missingImages??'—'}</strong></article><article><span>SIZE THIẾU GIÁ</span><strong>{isDemo?0:catalog?.missingPrices??'—'}</strong></article></section><section className="panel catalogInsights"><div><h3>Cơ cấu danh mục</h3>{catalog?.categoryBreakdown?.map((x:any)=><p key={x.category}><span>{x.category}</span><b>{x.count}</b></p>)}</div><div><h3>Size phổ biến</h3>{catalog?.sizeBreakdown?.slice(0,8).map((x:any)=><p key={x.size}><span>{x.size}</span><b>{x.count} mẫu</b></p>)}</div><div><h3>Mẫu có nhiều Size</h3>{catalog?.mostVariants?.map((x:any)=><p key={x.product_id}><span>{x.product_name}</span><b>{x.count} Size</b></p>)}</div></section><section className="panel"><div className="row"><h3>{active}</h3><div className="row"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm tên / mã / SKU"/>{active==='Danh mục sản phẩm'&&!isDemo&&<button className="primary" onClick={()=>setShowAdd(!showAdd)}>+ SẢN PHẨM</button>}</div></div>{showAdd&&active==='Danh mục sản phẩm'&&<AddProduct onDone={()=>{setShowAdd(false);setProductReload(x=>x+1)}}/>}<div className="productList">{products.map(p=><article className="product clickable" key={p.id} onClick={()=>{if(!isDemo){setDetailProductId(p.id);setOpsProductId(null)}}}><div className="catalogPhoto">{!isDemo&&p.image_id?<img loading="lazy" src={"/api/images/"+p.image_id} alt={"Ảnh "+p.name}/>:<span>Chưa có ảnh</span>}</div><div className="catalogInfo"><b>{p.product_code}</b><h3>{p.name}</h3><small>{p.category||"Chưa phân loại"} · {p.variant_count} size</small></div><strong>{p.total_stock}<small> tồn sổ sách</small></strong></article>)}{!products.length&&<p>Chưa có sản phẩm.</p>}</div>{detailProductId&&<ProductDetail productId={detailProductId} onClose={()=>setDetailProductId(null)}/>} {opsProductId&&<InventoryOps productId={opsProductId} onClose={()=>setOpsProductId(null)}/>}</section></>}
  {active==='Import kho'&&<section className="panel"><h3>Quét kho hiện hữu</h3><p>Chỉ đọc folder. Không ghi database cho đến khi duyệt.</p><div className="row"><input className="grow" value={root} onChange={e=>setRoot(e.target.value)} placeholder={'Ví dụ: D:\\1-Me CaCao Store'}/><button className="primary" onClick={doScan} disabled={busy}>{busy?'Đang quét...':'QUÉT KHO'}</button></div>{msg&&<p className="notice">{msg}</p>}{scan&&!draft&&<><div className="row"><p><b>{scan.productCount}</b> sản phẩm được phát hiện.</p><div className="row"><button onClick={()=>setBatchSelected(Object.fromEntries(scan.products.map((_,i)=>[i,true])))}>CHỌN TẤT CẢ</button><button onClick={()=>setBatchSelected({})}>BỎ CHỌN</button><button className="primary" disabled={busy} onClick={commitBatch}>{busy?(batchProgress?'ĐANG LƯU '+batchProgress:'ĐANG XỬ LÝ...'):'LƯU HÀNG LOẠT'}</button></div></div><div className="productList">{scan.products.map((p,i)=><article className="scanCard" key={p.name+i}><div className="row"><div className="row"><input type="checkbox" checked={!!batchSelected[i]} onChange={e=>setBatchSelected({...batchSelected,[i]:e.target.checked})}/><div><b>{p.suggestedProductCode}</b><h3>{p.name}</h3><small>{p.status==='EXISTING'?'ĐÃ NHẬP':p.status==='PARTIAL'?'CÒN SIZE MỚI':'CHƯA NHẬP'}</small></div></div><button className="primary" onClick={()=>editProduct(p)}>DUYỆT</button></div>{p.sizes.map(s=><div className="sizeRow" key={s.size}><span>{s.size}</span><small>{s.suggestedSku} · {s.images.length} ảnh</small></div>)}{p.warnings.map(w=><p className="warning" key={w}>{w}</p>)}</article>)}</div></>}
  {draft&&<div className="approval"><h3>Duyệt trước khi lưu</h3><div className="formGrid"><label>Tên sản phẩm<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Mã sản phẩm<input value={draft.productCode} onChange={e=>setDraft({...draft,productCode:e.target.value})}/></label><label>Danh mục<input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></label><label>Giá nhập<input type="number" min="0" value={draft.costPrice} onChange={e=>setDraft({...draft,costPrice:Number(e.target.value)||0})}/></label><label>Giá bán<input type="number" min="0" value={draft.salePrice} onChange={e=>setDraft({...draft,salePrice:Number(e.target.value)||0})}/></label></div><h4>Chọn / Size / SKU / Giá nhập / Giá bán / Tồn đầu đề xuất / Ảnh / Trạng thái</h4>{draft.variants.map((v,i)=><div className="variantEdit" key={i}><input type="checkbox" checked={v.selected} onChange={e=>{const variants=[...draft.variants];variants[i]={...v,selected:e.target.checked};setDraft({...draft,variants})}}/><input value={v.size} onChange={e=>updateVariant(i,'size',e.target.value)}/><input value={v.sku} onChange={e=>updateVariant(i,'sku',e.target.value)}/><input type="number" min="0" placeholder="Giá nhập size" value={v.costPrice} onChange={e=>updateVariant(i,'costPrice',e.target.value)}/><input type="number" min="0" placeholder="Giá bán size" value={v.salePrice} onChange={e=>updateVariant(i,'salePrice',e.target.value)}/><input type="number" min="0" placeholder="Tồn đầu" value={v.openingStock} onChange={e=>updateVariant(i,'openingStock',e.target.value)}/><small>{v.images.length} ảnh · {v.status==='EXISTING'?'ĐÃ NHẬP — không cộng lại tồn':'CHƯA NHẬP'}</small></div>)}<div className="row actions"><button onClick={()=>setDraft(null)}>QUAY LẠI</button><button className="primary" disabled={busy} onClick={commitDraft}>{busy?'ĐANG LƯU...':'XÁC NHẬN & LƯU'}</button></div></div>}</section>}
  </main></div></div>
}
