import {useEffect,useState} from 'react'
import {apiJson} from './uiState'
import './salesDrafts.css'
type Customer={id?:string;version?:number;name:string;phone:string;address:string;note:string}
const blank=():Customer=>({name:'',phone:'',address:'',note:''})
export default function CustomersView(){
 const [q,setQ]=useState(''),[rows,setRows]=useState<Customer[]>([]),[edit,setEdit]=useState<Customer>(blank),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[reload,setReload]=useState(0),[dirty,setDirty]=useState(false)
 useEffect(()=>{const c=new AbortController();setLoading(true);const t=setTimeout(()=>apiJson('/api/sales/drafts/customers?q='+encodeURIComponent(q),{signal:c.signal}).then(setRows).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading(false)}),180);return()=>{clearTimeout(t);c.abort()}},[q,reload])
 function choose(c:Customer){if(dirty&&!window.confirm('Bỏ thay đổi khách chưa lưu?'))return;setEdit({...c});setDirty(false);setError('');setMessage('')}
 async function save(allowDuplicate=false){if(busy)return;setBusy(true);setError('');setMessage('');try{const c=await apiJson('/api/sales/drafts/customers'+(edit.id?'/'+edit.id:''),{method:edit.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...edit,allowDuplicate})});setEdit(c);setDirty(false);setMessage('Đã lưu khách hàng');setReload(n=>n+1)}catch(e:any){if(e.data?.code==='CUSTOMER_DUPLICATE'&&window.confirm(e.message+' Tạo khách riêng?')){setBusy(false);void save(true);return}setError(e.message)}finally{setBusy(false)}}
 return <section className="salesDraftPage"><header className="salesHeading"><div><p className="eyebrow">SHOP MẸ CACAO</p><h2>Khách hàng</h2><p>Tìm, thêm và cập nhật thông tin khách để chọn nhanh khi chốt đơn.</p></div><button className="salesAction salesActionPrimary" disabled={busy} onClick={()=>choose(blank())}>＋ Khách mới</button></header><div className="salesWorkspace"><aside className="panel salesList"><label>Tìm tên / số điện thoại<input value={q} onChange={e=>setQ(e.target.value)} maxLength={100}/></label>{loading&&<p role="status">Đang tìm khách…</p>}{!loading&&!rows.length&&<p>Chưa có khách phù hợp.</p>}{rows.map(c=><button key={c.id} className="salesOrderRow" disabled={busy} onClick={()=>choose(c)}><span><b>{c.name}</b><small>{c.phone||'Chưa có điện thoại'}</small></span></button>)}</aside><section className="panel salesEditor contactCard"><h3>{edit.id?'Sửa thông tin khách':'Tạo khách hàng'}</h3><fieldset disabled={busy}>{(['name','phone','address','note'] as const).map((k,i)=><label key={k}>{['Tên khách *','Điện thoại','Địa chỉ giao hàng','Ghi chú'][i]}<input value={edit[k]} maxLength={k==='name'?100:k==='phone'?30:500} onChange={e=>{setEdit({...edit,[k]:e.target.value});setDirty(true)}}/></label>)}<button className="salesAction salesActionPrimary" disabled={!edit.name.trim()||!dirty} onClick={()=>void save()}>{busy?'Đang lưu…':'Lưu khách hàng'}</button></fieldset>{error&&<p role="alert" className="notice warning">{error}</p>}{message&&<p role="status">{message}</p>}</section></div></section>
}
