import {useEffect,useState} from 'react'
import {apiJson} from './uiState'
export type Contact={customerId:string|null;recipientName:string;phone:string;address:string;shippingFee:number}
type Customer={id:string;name:string;phone:string;address:string;note:string;version:number}
export default function CustomerContact({value,onChange,disabled}:{value:Contact;onChange:(c:Contact)=>void;disabled:boolean}){
 const [q,setQ]=useState(''),[customers,setCustomers]=useState<Customer[]>([]),[error,setError]=useState(''),[edit,setEdit]=useState<Partial<Customer>|null>(null),[saving,setSaving]=useState(false),[reload,setReload]=useState(0)
 useEffect(()=>{const c=new AbortController();const t=setTimeout(()=>{apiJson('/api/sales/drafts/customers?q='+encodeURIComponent(q),{signal:c.signal}).then(setCustomers).catch(e=>{if(!c.signal.aborted)setError(e.message)})},180);return()=>{clearTimeout(t);c.abort()}},[q,reload])
 const choose=(c:Customer)=>{onChange({...value,customerId:c.id,recipientName:c.name,phone:c.phone,address:c.address});setQ('')}
 async function save(allowDuplicate=false){if(!edit||saving)return;setSaving(true);setError('');try{const c=await apiJson('/api/sales/drafts/customers'+(edit.id?'/'+edit.id:''),{method:edit.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...edit,allowDuplicate})});choose(c);setEdit(null);setReload(n=>n+1)}catch(e:any){if(e.data?.code==='CUSTOMER_DUPLICATE'&&window.confirm(e.message+' Tạo khách riêng với số điện thoại này?')){setSaving(false);void save(true);return}setError(e.message)}finally{setSaving(false)}}
 return <section className="contactCard"><h3>Khách hàng & giao hàng</h3><fieldset disabled={disabled||saving}>
 <label>Tìm khách theo tên / điện thoại<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nhập tên hoặc số điện thoại"/></label>
 <div className="customerResults">{customers.slice(0,q?20:5).map(c=><div key={c.id}><button type="button" onClick={()=>choose(c)}>{c.name} · {c.phone||'Chưa có SĐT'}</button><button type="button" onClick={()=>setEdit({...c})}>Sửa khách</button></div>)}</div>
 <div className="salesButtons"><button type="button" onClick={()=>setEdit({name:value.recipientName,phone:value.phone,address:value.address,note:''})}>＋ Tạo khách</button><button type="button" onClick={()=>onChange({...value,customerId:null,recipientName:'',phone:'',address:''})}>Bỏ chọn khách</button></div>
 {edit&&<div className="customerForm"><h4>{edit.id?'Sửa khách hàng':'Khách hàng mới'}</h4>{(['name','phone','address','note'] as const).map((key,i)=><label key={key}>{['Tên khách','Điện thoại','Địa chỉ','Ghi chú khách'][i]}<input maxLength={key==='name'?100:key==='phone'?30:500} value={String(edit[key]??'')} onChange={e=>setEdit({...edit,[key]:e.target.value})}/></label>)}<button type="button" disabled={saving||!edit.name?.trim()} onClick={()=>void save()}>Lưu khách & chọn</button><button type="button" onClick={()=>setEdit(null)}>Đóng</button></div>}
 <div className="contactGrid"><label>Người nhận<input maxLength={100} value={value.recipientName} onChange={e=>onChange({...value,recipientName:e.target.value})}/></label><label>Điện thoại giao hàng<input maxLength={30} value={value.phone} onChange={e=>onChange({...value,phone:e.target.value})}/></label><label>Địa chỉ giao hàng<textarea maxLength={500} value={value.address} onChange={e=>onChange({...value,address:e.target.value})}/></label><label>Phí ship (đ)<input type="number" min="0" step="1" value={value.shippingFee} onChange={e=>onChange({...value,shippingFee:e.target.value===''?0:Number(e.target.value)})}/><button type="button" onClick={()=>onChange({...value,shippingFee:0})}>Miễn ship</button></label></div>
 </fieldset>{error&&<p role="alert" className="notice warning">{error}</p>}<small>Thông tin giao hàng được lưu riêng trong đơn; sửa danh mục khách không đổi đơn cũ.</small></section>
}
