import { useEffect,useState } from 'react'

type Product={id:number;product_code:string;name:string}
type SizeRow={size:string;sku:string;quantity:number;costPrice:number;salePrice:number;sourcePath:string;imageCount:number}
type Progress={phase:string;percent:number;copied:number;total:number;current?:string}
const blank=():SizeRow=>({size:'',sku:'',quantity:1,costPrice:0,salePrice:0,sourcePath:'',imageCount:0})
const labels:Record<string,string>={VALIDATE:'Kiểm tra dữ liệu',PREPARE:'Chuẩn bị thư mục kho',COPY:'Copy ảnh vào kho',VERIFY:'Kiểm tra ảnh',DB_COMMIT:'Ghi Product / SKU / Ledger',INTEGRITY:'Kiểm tra toàn vẹn',DONE:'Hoàn tất',ROLLBACK:'Hoàn tác'}

export default function GoodsReceipt(){
 const [products,setProducts]=useState<Product[]>([]),[productId,setProductId]=useState(0),[newMode,setNewMode]=useState(false)
 const [name,setName]=useState(''),[code,setCode]=useState(''),[category,setCategory]=useState(''),[storeRoot,setStoreRoot]=useState(''),[rows,setRows]=useState<SizeRow[]>([blank()]),[note,setNote]=useState('')
 const [busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[progress,setProgress]=useState<Progress|null>(null)
 useEffect(()=>{fetch('/api/products').then(r=>r.json()).then(setProducts).catch(()=>{})},[])
 async function chooseProduct(id:number){setProductId(id);setNewMode(false);setMsg('');if(!id)return;const r=await fetch('/api/products/'+id);const j=await r.json();if(r.ok){setName(j.product.name);setCode(j.product.product_code);setRows(j.variants.map((v:any)=>({size:v.size,sku:v.sku,quantity:1,costPrice:v.cost_price??0,salePrice:v.sale_price??0,sourcePath:'',imageCount:0})))}}
 function patch(i:number,k:keyof SizeRow,v:string|number){const a=[...rows];a[i]={...a[i],[k]:typeof a[i][k]==='number'?Math.max(0,Number(v)||0):v};setRows(a)}
 async function inspect(i:number){const p=rows[i].sourcePath.trim();if(!p){setMsg('Nhập đường dẫn folder ảnh của size.');return}const r=await fetch('/api/goods-receipt/inspect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:p})});const j=await r.json();if(!r.ok){setMsg(j.error||'Không đọc được folder ảnh');return}const a=[...rows];a[i]={...a[i],imageCount:j.count,quantity:j.count||a[i].quantity};setRows(a);setMsg(j.count+' ảnh hợp lệ — đã đề xuất SL '+j.count)}
 async function submit(){if(busy)return;setBusy(true);setMsg('');setProgress({phase:'VALIDATE',percent:2,copied:0,total:rows.reduce((n,r)=>n+r.imageCount,0)})
  try{const payload={storeRoot,productId:newMode?undefined:productId||undefined,name,productCode:code,category,note,sizes:rows.filter(r=>r.size.trim()).map(r=>({size:r.size,sku:r.sku||undefined,quantity:Math.trunc(r.quantity),costPrice:Math.trunc(r.costPrice),salePrice:Math.trunc(r.salePrice),sourcePath:r.sourcePath||undefined}))};const r=await fetch('/api/goods-receipt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Nhập hàng thất bại');for(const e of j.events??[]){setProgress(e);await new Promise(x=>setTimeout(x,80))}setMsg('Nhập thành công: '+j.result.totalQuantity+' bộ · '+j.result.copiedImages+' ảnh đã copy vào kho.')}catch(e){setMsg(e instanceof Error?e.message:'Nhập hàng thất bại')}finally{setBusy(false)}
 }
 return <section className="receipt">
  <div className="row"><div><h3>Nhập hàng về kho</h3><p>Ảnh nguồn được COPY thật vào kho Product / Size. Số ảnh chỉ là SL đề xuất; SL xác nhận mới ghi ledger.</p></div><button onClick={()=>{setNewMode(true);setProductId(0);setName('');setCode('');setRows([blank()])}}>+ MẪU MỚI</button></div>
  <div className="formGrid"><label>Kho đích<input value={storeRoot} onChange={e=>setStoreRoot(e.target.value)} placeholder={'D:\\1-Me CaCao Store'}/></label><label>Hàng đã có<select value={productId} onChange={e=>void chooseProduct(Number(e.target.value))}><option value="0">-- Chọn Product --</option>{products.map(p=><option key={p.id} value={p.id}>{p.product_code} · {p.name}</option>)}</select></label><label>Tên sản phẩm<input disabled={!newMode} value={name} onChange={e=>setName(e.target.value)}/></label><label>Mã sản phẩm<input disabled={!newMode} value={code} onChange={e=>setCode(e.target.value)} placeholder="Để trống = tự đề xuất"/></label><label>Danh mục<input disabled={!newMode} value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Ghi chú<input value={note} onChange={e=>setNote(e.target.value)}/></label></div>
  <h4>Size / SKU / Folder ảnh nguồn / Ảnh / SL xác nhận / Giá nhập / Giá bán</h4>
  {rows.map((x,i)=><div className="receiptRow" key={i}><input value={x.size} onChange={e=>patch(i,'size',e.target.value)} placeholder="Size"/><input value={x.sku} onChange={e=>patch(i,'sku',e.target.value)} placeholder="SKU tự động"/><div className="row"><input className="grow" value={x.sourcePath} onChange={e=>patch(i,'sourcePath',e.target.value)} placeholder="Folder ảnh (có thể để trống)"/><button onClick={()=>void inspect(i)} disabled={busy}>ĐẾM ẢNH</button></div><span>{x.imageCount} ảnh</span><input type="number" min="1" value={x.quantity} onChange={e=>patch(i,'quantity',Math.max(1,Math.trunc(Number(e.target.value)||1)))}/><input type="number" min="0" value={x.costPrice} onChange={e=>patch(i,'costPrice',e.target.value)}/><input type="number" min="0" value={x.salePrice} onChange={e=>patch(i,'salePrice',e.target.value)}/></div>)}
  <div className="row actions"><button onClick={()=>setRows([...rows,blank()])}>+ SIZE MỚI</button><button className="primary" disabled={busy||!storeRoot||(!productId&&!newMode)} onClick={()=>void submit()}>{busy?'ĐANG NHẬP...':'XÁC NHẬN NHẬP HÀNG'}</button></div>
  {progress&&<div className="progressBox"><div className="row"><b>{labels[progress.phase]??progress.phase}</b><strong>{progress.percent}%</strong></div><progress max="100" value={progress.percent}/><small>{progress.total?progress.copied+'/'+progress.total+' ảnh':''}{progress.current?' · '+progress.current:''}</small></div>}
  {msg&&<p className="notice">{msg}</p>}
 </section>
}
