import {useEffect,useRef,useState} from 'react'
import {apiJson} from './uiState'
type Row={id:number;oldPath:string;newPath:string;product:string;size:string;sha256:string}
export default function ImageRename({rootPath,onChanged,onBusy}:{rootPath:string;onChanged:()=>void;onBusy:(value:boolean)=>void}){
 const [plan,setPlan]=useState<any>(null),[selected,setSelected]=useState<Set<number>>(new Set()),[confirmation,setConfirmation]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[logs,setLogs]=useState<any[]>([]),lock=useRef(false)
 useEffect(()=>{setPlan(null);setConfirmation(null);setSelected(new Set());setError('')},[rootPath])
 const request=(data:unknown)=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})
 async function inspect(ids?:number[]){if(lock.current)return;lock.current=true;setBusy(true);onBusy(true);setError('');try{const p=await apiJson('/api/warehouse/rename/preview',request({rootPath,ids}));if(ids)setConfirmation(p);else{setPlan(p);setSelected(new Set(p.files.map((r:Row)=>r.id)));setConfirmation(null)}setLogs(await apiJson('/api/warehouse/rename/logs'))}catch(e){setError(e instanceof Error?e.message:'Không kiểm tra được')}finally{lock.current=false;setBusy(false);onBusy(false)}}
 async function commit(){if(lock.current||!confirmation)return;lock.current=true;setBusy(true);onBusy(true);setError('');try{const r=await apiJson('/api/warehouse/rename/commit',request({rootPath,ids:[...selected],token:confirmation.token,confirmed:true}));setMessage('Đã đổi tên '+r.renamed+' ảnh; nội dung và ID được giữ nguyên. Nhật ký: '+(r.log??'không có thay đổi'));setPlan(null);setConfirmation(null);setSelected(new Set());setLogs(await apiJson('/api/warehouse/rename/logs'));onChanged()}catch(e){setConfirmation(null);setError(e instanceof Error?e.message:'Rename thất bại; kiểm tra nhật ký trước khi thử lại')}finally{lock.current=false;setBusy(false);onBusy(false)}}
 function csv(log:any){const cell=(v:unknown)=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const data='\ufeffID,Product,Size,OldPath,NewPath,SHA256,Outcome\r\n'+log.files.map((f:Row)=>[f.id,f.product,f.size,f.oldPath,f.newPath,f.sha256,log.outcome].map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='rename-'+log.id+'.csv';a.click();URL.revokeObjectURL(url)}
 return <section className="renameWorkspace"><h3>FILE ẢNH THẬT / AUTO RENAME</h3><p>Kiểm tra ảnh đã đăng ký trong kho. Ảnh mới chưa đăng ký cần duyệt import trước. Tên chưa chuẩn vẫn được tính tồn.</p><button disabled={busy} onClick={()=>inspect()}>KIỂM TRA TÊN FILE KHO</button>{busy&&<p role="status">Đang xác minh checksum/tên ảnh...</p>}{error&&<p className="notice warning" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}
 {plan&&<><div className="warehouseMetrics"><article><span>ẢNH ĐÃ ĐĂNG KÝ</span><strong>{plan.summary.registered}</strong></article><article><span>ĐÚNG CHUẨN</span><strong>{plan.summary.correct}</strong></article><article><span>CẦN ĐỔI TÊN</span><strong>{plan.summary.pending}</strong></article><article><span>FILE BỊ THIẾU</span><strong>{plan.summary.missing}</strong></article></div><button disabled={busy} onClick={()=>{setSelected(new Set(plan.files.map((r:Row)=>r.id)));setConfirmation(null)}}>CHỌN TẤT CẢ</button><button disabled={busy} onClick={()=>{setSelected(new Set());setConfirmation(null)}}>BỎ CHỌN</button><p>Hiển thị tối đa 100 dòng; CSV xem trước chứa toàn bộ kế hoạch.</p><button onClick={()=>csv({id:'preview',files:plan.files,outcome:'PREVIEW'})}>XUẤT CSV XEM TRƯỚC</button><div className="renameRows">{plan.files.slice(0,100).map((r:Row)=><label key={r.id}><input disabled={busy} type="checkbox" checked={selected.has(r.id)} onChange={e=>{const ids=new Set(selected);e.target.checked?ids.add(r.id):ids.delete(r.id);setSelected(ids);setConfirmation(null)}}/><b>{r.product} · {r.size}</b><code>{r.oldPath}</code><span>→</span><code>{r.newPath}</code></label>)}</div><button disabled={busy||!selected.size} onClick={()=>inspect([...selected])}>XEM TRƯỚC {selected.size} ẢNH ĐÃ CHỌN</button></>}
 {confirmation&&<div className="warehouseConfirm" role="region" aria-label="Xác nhận rename"><h4>Xác nhận đổi tên {confirmation.files.length} FILE ẢNH THẬT</h4><p>Chỉ đổi tên file trong cùng thư mục, cập nhật đường dẫn DB, giữ ID/checksum/số tồn. Có backup DB và nhật ký phục hồi. Không đổi ảnh nguồn nhập hàng hoặc thư mục.</p>{confirmation.files.slice(0,50).map((r:Row)=><p key={r.id}>{r.newPath}</p>)}<button className="primary" disabled={busy||!!confirmation.missing.length} onClick={commit}>XÁC NHẬN RENAME FILE ẢNH THẬT</button><button disabled={busy} onClick={()=>setConfirmation(null)}>HỦY</button></div>}
 {!!logs.length&&<details><summary>Nhật ký rename / Xuất CSV</summary>{logs.map(log=><div className="batchOutcome" key={log.id}><span>{log.createdAt} · {log.outcome} · {log.files.length} ảnh</span><button onClick={()=>csv(log)}>TẢI CSV ĐỐI CHIẾU</button></div>)}</details>}
 </section>
}
