import {useEffect,useRef,useState} from 'react'
import {apiJson} from './uiState'
import './orderFinance.css'
const vnd=(n:number|bigint)=>n.toLocaleString('vi-VN')+' đ'
const methodNames:Record<string,string>={COD:'COD',TRANSFER:'Chuyển khoản',CASH:'Tiền mặt'}
const deliveryNames:Record<string,string>={NEW:'Chưa giao',SHIPPED:'Đang giao',DELIVERED:'Đã giao',FAILED:'Giao thất bại'}
const kindNames:Record<string,string>={RECEIPT:'Thu tiền',REFUND:'Hoàn tiền',CREDIT:'Điều chỉnh giảm',RETURN:'Trả hàng',EXCHANGE:'Đổi hàng',SUPPORT:'Hỗ trợ'}
export default function OrderFinance({id,disabled,onChanged}:{id:string;disabled:boolean;onChanged:()=>void}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[method,setMethod]=useState('COD'),[receiptMethod,setReceiptMethod]=useState('COD'),[delivery,setDelivery]=useState('NEW'),[tracking,setTracking]=useState('')
 const [kind,setKind]=useState('RECEIPT'),[amount,setAmount]=useState(''),[note,setNote]=useState(''),[caseKind,setCaseKind]=useState('SUPPORT'),[caseNote,setCaseNote]=useState(''),[resolution,setResolution]=useState<Record<string,string>>({})
 const pendingKey='mecacao-finance-pending-'+id
 const [pending,setPending]=useState<any>(()=>{try{return JSON.parse(localStorage.getItem(pendingKey)||'null')}catch{return null}})
 const lock=useRef(false),retry=useRef<{payload:string;key:string}|null>(null)
 useEffect(()=>{const c=new AbortController();setError('');apiJson('/api/sales/drafts/'+id+'/finance',{signal:c.signal}).then(s=>{if(c.signal.aborted)return;setData(s);setMethod(s.method);setReceiptMethod(s.method);setDelivery(s.delivery);setTracking(s.tracking)}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[id,reload])
 useEffect(()=>{const changed=()=>{if(lock.current||busy||pending)setError('Có giao dịch khác trên máy chủ. Chưa thay đổi chứng từ đang xử lý; đối chiếu sổ trước khi ghi tiếp.');else setReload(n=>n+1)};window.addEventListener('mecacao-server-change',changed);return()=>window.removeEventListener('mecacao-server-change',changed)},[busy,pending])
 async function write(route:string,body:any,verb='POST',idempotent=false){
  if(lock.current||disabled||!data||pending)return;lock.current=true;setBusy(true);setError('')
  const payload=JSON.stringify({...body,version:data.version,orderVersion:data.orderVersion})
  if(idempotent&&retry.current?.payload!==route+payload)retry.current={payload:route+payload,key:crypto.randomUUID()}
  const intent={route,body:payload,key:retry.current?.key,verb}
  try{if(idempotent){localStorage.setItem(pendingKey,JSON.stringify(intent));setPending(intent)}const s=await apiJson('/api/sales/drafts/'+id+route,{method:verb,headers:{'Content-Type':'application/json',...(idempotent?{'Idempotency-Key':retry.current!.key}:{})},body:payload});setData(s);setAmount('');setNote('');setCaseNote('');retry.current=null;if(idempotent){localStorage.removeItem(pendingKey);setPending(null)}onChanged()}catch(e:any){if(idempotent&&e.status>=400&&e.status<500){localStorage.removeItem(pendingKey);setPending(null)}setError(e instanceof Error?e.message:'Chưa ghi nhận. Thử lại cùng yêu cầu hoặc mở lại sổ để kiểm tra.')}finally{lock.current=false;setBusy(false)}
 }
 async function resume(){if(lock.current||!pending||disabled)return;lock.current=true;setBusy(true);try{const s=await apiJson('/api/sales/drafts/'+id+pending.route,{method:pending.verb,headers:{'Content-Type':'application/json','Idempotency-Key':pending.key},body:pending.body});setData(s);localStorage.removeItem(pendingKey);setPending(null);setError('');onChanged()}catch(e:any){if(e.status>=400&&e.status<500){localStorage.removeItem(pendingKey);setPending(null)}setError(e.message)}finally{lock.current=false;setBusy(false)}}
 const unavailable=disabled||busy||!!pending||!data||data.orderStatus==='CANCELLED_DRAFT'
 return <section className="financePanel" aria-label="Thanh toán và hậu mãi"><div className="row"><h3>Thanh toán & giao hàng</h3><button disabled={busy} onClick={()=>setReload(n=>n+1)}>Mở lại sổ</button></div><p>Bán hàng, giao hàng và thu tiền được ghi riêng. Có thể ghi tiền cọc ở đơn nháp.</p>{pending&&<div className="notice warning"><p>Có chứng từ chưa xác minh kết quả. Tiếp tục cùng mã yêu cầu trước khi tạo chứng từ khác.</p><button disabled={busy||disabled} onClick={()=>void resume()}>Tiếp tục yêu cầu đang chờ</button></div>}{error&&<p className="notice warning" role="alert">{error}</p>}{!data&&!error&&<p role="status">Đang đọc sổ thanh toán…</p>}{data&&<><div className="financeMetrics"><div><small>Giá trị sau điều chỉnh</small><b>{vnd(data.adjustedTotal)}</b></div><div><small>Đã thu sau hoàn</small><b>{vnd(data.netCollected)}</b></div><div><small>Còn phải thu</small><b>{vnd(data.due)}</b></div>{data.refundDue>0&&<div><small>Cần hoàn khách</small><b>{vnd(data.refundDue)}</b></div>}</div><fieldset disabled={unavailable}><div className="financeGrid"><label>Hình thức dự kiến<select aria-label="Hình thức thanh toán" value={method} onChange={e=>setMethod(e.target.value)}>{Object.entries(methodNames).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Giao hàng<select value={delivery} onChange={e=>setDelivery(e.target.value)}>{Object.entries(deliveryNames).filter(([v])=>data.orderStatus==='SOLD'||v==='NEW').map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Mã vận đơn<input value={tracking} maxLength={150} onChange={e=>setTracking(e.target.value)}/></label></div><button className="salesAction salesActionPrimary" disabled={method===data.method&&delivery===data.delivery&&tracking===data.tracking} onClick={()=>void write('/finance',{method,delivery,tracking},'PUT')}>Lưu hình thức / giao hàng</button></fieldset>
 <details className="financeEntryForm" open><summary>Ghi thu / hoàn tiền / điều chỉnh</summary><fieldset disabled={unavailable}><div className="financeGrid"><label>Loại chứng từ<select aria-label="Loại chứng từ" value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(kindNames).filter(([v])=>['RECEIPT','REFUND',...(data.orderStatus==='SOLD'?['CREDIT']:[])].includes(v)).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Số tiền (đ)<input aria-label="Số tiền chứng từ" inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Hình thức thực tế<select aria-label="Hình thức chứng từ" value={receiptMethod} onChange={e=>setReceiptMethod(e.target.value)}>{Object.entries(methodNames).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Nội dung *<input aria-label="Nội dung chứng từ" value={note} maxLength={500} onChange={e=>setNote(e.target.value)}/></label></div><p>Chứng từ đã ghi giữ nguyên. Điều chỉnh giảm sau bán có thể phát sinh số tiền cần hoàn khách; ghi hoàn tiền khi thực hiện hoàn.</p><button className="salesAction salesActionPrimary" disabled={!/^\d+$/.test(amount)||!Number.isSafeInteger(Number(amount))||Number(amount)<=0||!note.trim()} onClick={()=>void write('/finance/entries',{kind,amount:Number(amount),method:receiptMethod,note},'POST',true)}>Ghi chứng từ</button></fieldset></details>
 <div className="financeHistory"><h4>Lịch sử thu / hoàn / điều chỉnh</h4>{!data.entries.length&&<p>Chưa ghi nhận thanh toán.</p>}{data.entries.map((e:any)=><article key={e.id}><b>{kindNames[e.kind]} · {vnd(e.amount)}</b><span>{methodNames[e.method]} · {e.created_at}</span><small>{e.note}</small></article>)}</div>
 {data.orderStatus==='SOLD'&&<details className="aftercarePanel"><summary>Hậu mãi · đổi / trả / hỗ trợ ({data.cases.filter((c:any)=>c.status==='OPEN').length} đang mở)</summary><p>Ghi yêu cầu và kết quả xử lý. Phiếu hậu mãi không tự nhập hàng trở lại kho; hàng thực nhận lại cần chụp ảnh mới và duyệt qua Nhập hàng; hàng đổi xuất bằng đơn mới.</p><fieldset disabled={unavailable}><label>Loại yêu cầu<select value={caseKind} onChange={e=>setCaseKind(e.target.value)}>{['RETURN','EXCHANGE','SUPPORT'].map(v=><option key={v} value={v}>{kindNames[v]}</option>)}</select></label><label>Nội dung<input value={caseNote} maxLength={500} onChange={e=>setCaseNote(e.target.value)}/></label><button disabled={!caseNote.trim()} onClick={()=>void write('/aftercare',{kind:caseKind,note:caseNote},'POST',true)}>Tạo yêu cầu hậu mãi</button>{data.cases.map((c:any)=><article key={c.id}><b>{kindNames[c.kind]} · {c.status==='OPEN'?'Đang xử lý':'Đã xử lý'}</b><p>{c.note}</p>{c.status==='OPEN'?<><label>Kết quả xử lý<input value={resolution[c.id]??''} maxLength={500} onChange={e=>setResolution({...resolution,[c.id]:e.target.value})}/></label><button disabled={!resolution[c.id]?.trim()} onClick={()=>void write('/aftercare/'+c.id,{caseVersion:c.version,resolution:resolution[c.id]},'PUT')}>Hoàn tất xử lý</button></>:<p>{c.resolution}</p>}</article>)}</fieldset></details>}{disabled&&<p>Lưu thay đổi của đơn trước khi ghi thanh toán hoặc hậu mãi.</p>}{busy&&<p role="status">Đang ghi chứng từ…</p>}</>}</section>
}
export function DebtsView({onOrder}:{onOrder:(id:string)=>void}){
 const [rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(true),[reload,setReload]=useState(0),[q,setQ]=useState('')
 useEffect(()=>{const c=new AbortController();setBusy(true);setError('');apiJson('/api/sales/drafts/finance/debts',{signal:c.signal}).then(setRows).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted)setBusy(false)});return()=>c.abort()},[reload])
 useEffect(()=>{const changed=()=>setReload(n=>n+1);window.addEventListener('mecacao-server-change',changed);return()=>window.removeEventListener('mecacao-server-change',changed)},[])
 const groups=new Map<string,{name:string;due:bigint;refund:bigint;orders:number}>();for(const r of rows){const key=r.customerId??r.orderId,g=groups.get(key)??{name:r.recipientName||'Khách chưa chọn',due:0n,refund:0n,orders:0};g.due+=BigInt(r.due);g.refund+=BigInt(r.refundDue);g.orders++;groups.set(key,g)}
 const filtered=rows.filter(r=>(r.recipientName+' '+r.phone+' '+r.orderId).toLowerCase().includes(q.toLowerCase()))
 return <section className="salesDraftPage"><header className="salesHeading"><div><h2>Công nợ & cần hoàn khách</h2><p>Chỉ tính đơn đã bán. Tiền cọc nháp xem trong đơn; không coi là công nợ đã bán.</p></div><button onClick={()=>setReload(n=>n+1)}>Làm mới</button></header><div className="financeMetrics"><div><small>Tổng còn phải thu</small><b>{vnd(rows.reduce((n,r)=>n+BigInt(r.due),0n))}</b></div><div><small>Tổng cần hoàn</small><b>{vnd(rows.reduce((n,r)=>n+BigInt(r.refundDue),0n))}</b></div><div><small>Đơn cần xử lý</small><b>{rows.length}</b></div></div>{error&&<p role="alert" className="notice warning">{error}</p>}{busy&&<p role="status">Đang tổng hợp…</p>}<section className="panel"><h3>Theo khách hàng</h3>{[...groups.entries()].map(([k,g])=><article className="debtCustomer" key={k}><b>{g.name} · {g.orders} đơn</b><span>Phải thu {vnd(g.due)} · cần hoàn {vnd(g.refund)}</span></article>)}{!busy&&!rows.length&&!error&&<p>Không có công nợ hoặc tiền cần hoàn ở đơn đã bán.</p>}<label>Tìm khách / điện thoại / mã đơn<input value={q} onChange={e=>setQ(e.target.value)}/></label>{filtered.map(r=><button className="debtOrder" key={r.orderId} onClick={()=>onOrder(r.orderId)}><span><b>{r.orderId.slice(0,8).toUpperCase()} · {r.recipientName||'Chưa chọn khách'}</b><small>{r.phone} · {methodNames[r.method]} · {deliveryNames[r.delivery]}</small></span><strong>Thu {vnd(r.due)}{r.refundDue>0?' · hoàn '+vnd(r.refundDue):''} →</strong></button>)}</section></section>
}
