import {useEffect,useState} from 'react'
import GoodsReceipt from './GoodsReceipt'
type D={transactions:number;importedQuantity:number;importedValue:number;lastImport:string|null;top:{productId:number;name:string;code:string;quantity:number;value:number}[];recent:{id:number;productName:string;size:string;quantity:number;createdAt:string}[]}
const demo:D={transactions:8,importedQuantity:32,importedValue:1152000,lastImport:'2026-10-07 16:30',top:[{productId:1,name:'Bộ tole bé gái hoa',code:'BG001',quantity:18,value:648000},{productId:2,name:'Bộ tole bé trai',code:'BT002',quantity:14,value:504000}],recent:[{id:1,productName:'Bộ tole bé gái hoa',size:'Size 5',quantity:8,createdAt:'2026-10-07 16:30'}]}
const num=(n:number)=>new Intl.NumberFormat('vi-VN').format(n)
export default function ReceiptDashboard({isDemo}:{isDemo:boolean}){
 const [data,setData]=useState<D|null>(isDemo?demo:null),[error,setError]=useState('')
 useEffect(()=>{if(isDemo)return;let active=true;fetch('/api/goods-receipt/dashboard').then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error||'Lỗi báo cáo');if(active)setData(j)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[isDemo])
 const stats:[string,string,string][]=[['LƯỢT NHẬP',data?num(data.transactions):'—','Giao dịch nhập đã ghi'],['ĐÃ NHẬP',data?num(data.importedQuantity):'—','Tổng số lượng nhập lũy kế'],['GIÁ TRỊ NHẬP',data?num(data.importedValue)+' đ':'—','Tổng giá vốn lúc nhập'],['LẦN NHẬP GẦN NHẤT',data?.lastImport||'Chưa có','Ngày giờ ghi nhận']]
 return <section className="receiptOverview"><div className="receiptIntro"><div><p className="eyebrow">QUẢN LÝ NHẬP HÀNG</p><h2>Thống kê nhập hàng</h2><p>Hoạt động nhập hàng, mẫu nhập nhiều và lịch sử mới nhất.</p></div>{isDemo&&<b className="overviewDemoLabel">SỐ LIỆU MINH HỌA</b>}</div>{error&&<p role="alert">{error}</p>}<div className="receiptStats">{stats.map(([label,value,detail])=><article key={label}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>)}</div><div className="receiptCharts"><article className="insightCard"><h3>Mẫu nhập nhiều nhất</h3>{data?.top.length?data.top.map(x=><div className="receiptTop" key={x.productId}><b>{x.name}</b><small>{x.code} · {num(x.value)} đ</small><div className="receiptTrack"><i style={{width:(100*x.quantity/Math.max(...data.top.map(y=>y.quantity)))+'%'}}/></div><strong>{num(x.quantity)} bộ</strong></div>):<p>Chưa có giao dịch nhập.</p>}</article><article className="insightCard"><h3>Nhập hàng gần đây</h3>{data?.recent.length?data.recent.map(x=><div className="receiptRecent" key={x.id}><div><b>{x.productName}</b><small>{x.size} · {x.createdAt}</small></div><strong>+{num(x.quantity)}</strong></div>):<p>Chưa có giao dịch nhập.</p>}</article></div><p className="receiptNote">Số lượng và giá trị nhập là <b>lịch sử giao dịch</b>, không phải tồn kho hiện tại. Tồn thực tế chỉ tính theo ảnh vật lý đã đăng ký.</p>{isDemo?<div className="receiptDemoNotice"><h3>Chế độ xem thử</h3><p>DEMO chỉ xem giao diện minh họa. Để nhập hàng và đọc ảnh kho ổ D:, sử dụng LOCAL trên Windows.</p></div>:<GoodsReceipt/>}</section>
}