import {useEffect,useRef,useState} from 'react'
import {apiJson} from './uiState'
import FolderPicker from './FolderPicker'
import './restoreTest.css'
type Result={status:string;targetRoot:string;warehouse:string;schema:number;backupVersion?:number;imagesVerified:number;archiveFilesVerified:number;counts?:Record<string,number>}
export default function RestoreTestPanel({directory,busyParent,onBusy}:{directory:string;busyParent:boolean;onBusy:(busy:boolean)=>void}){
 const [warehouse,setWarehouse]=useState(''),[picker,setPicker]=useState(false),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Result|null>(null),lock=useRef(false)
 useEffect(()=>{let alive=true;apiJson('/api/warehouse/settings').then(s=>{if(alive)setWarehouse(s.rootPath||'')}).catch(()=>{});return()=>{alive=false}},[])
 useEffect(()=>{setConfirmed(false);setResult(null);setError('')},[directory])
 async function restore(){if(lock.current||!confirmed||!directory||!warehouse)return;lock.current=true;setBusy(true);onBusy(true);setError('');setResult(null);try{setResult(await apiJson('/api/backup/restore-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({directory,warehouseRoot:warehouse,confirmed:true})}))}catch(e){setError(e instanceof Error?e.message:'Không phục hồi được; giữ thư mục dở để kiểm tra')}finally{lock.current=false;setBusy(false);onBusy(false)}}
 return <section className="restoreTestPanel"><header><div><p className="eyebrow">KIỂM CHỨNG PHỤC HỒI</p><h3>Phục hồi thử sang kho mới</h3><p>Sao chép backup vào thư mục thử riêng, giữ nguyên kho và database đang chạy.</p></div><span>DB + ảnh gốc + bộ ảnh nhẹ</span></header><label>Backup đầy đủ vừa tạo<input readOnly value={directory} placeholder="Tạo backup đầy đủ ở phía trên trước"/></label><label>Kho gốc của ảnh trong backup<div className="restorePathRow"><input value={warehouse} disabled={busy||busyParent} onChange={e=>{setWarehouse(e.target.value);setConfirmed(false)}} placeholder="Chọn đúng thư mục kho hiện tại"/><button className="restoreSecondary" disabled={busy||busyParent} onClick={()=>setPicker(true)}>Chọn kho</button></div></label><label className="restoreConfirm"><input type="checkbox" checked={confirmed} disabled={busy||busyParent} onChange={e=>setConfirmed(e.target.checked)}/><span>Tạo một kho phục hồi thử mới; chưa chuyển ứng dụng sang sử dụng kho này.</span></label><button className="restorePrimary" disabled={busy||busyParent||!directory||!warehouse||!confirmed} onClick={()=>void restore()}>{busy?'Đang copy và kiểm chứng…':'Phục hồi & kiểm chứng'}</button>{busy&&<p role="status">Đang kiểm tra checksum, đường dẫn và quan hệ database. Không tắt cửa sổ server.</p>}{error&&<p className="notice warning" role="alert">{error}</p>}{result&&<div className="restoreResult" role="status"><b>✓ Kho thử READY · schema {result.schema}</b><div><span>{result.imagesVerified} ảnh gốc</span><span>{result.archiveFilesVerified} file bộ ảnh nhẹ</span><span>{result.counts?.sales_orders??0} đơn và lịch sử</span></div><p>{result.targetRoot}</p><p>Chạy {result.backupVersion===4?'RUN_WINDOWS_RESTORED_LOCAL_V2_TEST.bat':result.schema===130?'RUN_WINDOWS_RESTORED_V2_SALES_TEST.bat':'RUN_WINDOWS_RESTORED_SANDBOX_TEST.bat'} để mở kho thử mới trên cổng 3016. Đối chiếu tồn, đơn nháp, ảnh và kiểm chứng bộ ảnh nhẹ.</p></div>}{picker&&<FolderPicker title="Chọn kho gốc hiện tại" onPick={p=>{setWarehouse(p);setPicker(false);setConfirmed(false)}} onClose={()=>setPicker(false)}/>}</section>
}
