import {useEffect,useRef,useState} from 'react'
import {apiJson} from './uiState'
import './salesConfirmTrial.css'
type Result={status:string;quantity?:number;total?:number;originalBytes?:number;optimizedBytes?:number;message?:string;canRecover?:boolean;createdAt?:string}
export default function SalesConfirmTrial({id,version,token,zeroPrices,disabled,onBusy}:{id:string;version:number;token:string;zeroPrices:number;disabled:boolean;onBusy:(v:boolean)=>void}){
 const [confirmed,setConfirmed]=useState(false),[zero,setZero]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Result|null>(null)
 const lock=useRef(false),alive=useRef(true),request=useRef(''),storage='mecacao-confirm-trial:'+id+':'+version+':'+token
 useEffect(()=>{alive.current=true;try{request.current=localStorage.getItem(storage)||''}catch{}if(request.current)void inspect();return()=>{alive.current=false;onBusy(false)}},[storage])
 async function inspect(){
  if(!request.current||lock.current)return;lock.current=true;setBusy(true);onBusy(true);setError('')
  try{const r=await apiJson('/api/sales/drafts/'+id+'/confirm-trials/'+request.current);if(alive.current)setResult(r)}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Không đọc được trạng thái')}finally{lock.current=false;if(alive.current){setBusy(false);onBusy(false)}}
 }
 async function confirm(){
  if(lock.current||disabled||!confirmed||(zeroPrices>0&&!zero))return
  lock.current=true;setBusy(true);onBusy(true);setError('')
  if(!request.current){request.current='trial-'+crypto.randomUUID();try{localStorage.setItem(storage,request.current)}catch{}}
  try{const r=await apiJson('/api/sales/drafts/'+id+'/confirm-trial',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':request.current},body:JSON.stringify({version,token,confirmed:true,acknowledgeZeroPrice:zeroPrices>0?true:false})});if(alive.current)setResult(r)}catch(e){if(alive.current)setError((e instanceof Error?e.message:'Chưa nhận được kết quả')+'. Dùng Kiểm tra trạng thái để xác minh; không tạo mã thử mới khi chưa rõ kết quả.')}finally{lock.current=false;if(alive.current){setBusy(false);onBusy(false)}}
 }
 async function recover(){
  if(lock.current||!result?.canRecover)return;lock.current=true;setBusy(true);onBusy(true);setError('')
  try{const r=await apiJson('/api/sales/drafts/'+id+'/confirm-trials/'+request.current+'/recover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmed:true})});if(alive.current)setResult({...r,message:'Ảnh bản sao đã được phục hồi. Kho đang dùng giữ nguyên.'})}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Cần kiểm tra bản thử')}finally{lock.current=false;if(alive.current){setBusy(false);onBusy(false)}}
 }
 function fresh(){if(lock.current)return;request.current='';try{localStorage.removeItem(storage)}catch{}setResult(null);setError('');setConfirmed(false);setZero(false)}
 const running=result?.status==='RUNNING',done=result?.status==='SOLD_TRIAL',restored=result?.status==='RESTORED_TRIAL'
 return <section className="confirmTrial"><header><div><span className="confirmTrialBadge">CHỈ BẢN SAO · KHÔNG BÁN KHO ĐANG DÙNG</span><h4>Thử xác nhận toàn đơn</h4><p>Tạo database và ảnh riêng để kiểm tra giao dịch, lịch sử và phục hồi.</p></div></header>{!done&&!restored&&<><label className="confirmTrialChoice"><input className="confirmTrialCheckbox" type="checkbox" checked={confirmed} disabled={busy||disabled} onChange={e=>setConfirmed(e.target.checked)}/><span>Tôi hiểu lần thử chỉ bán trên bản sao. Nháp và tồn đang dùng vẫn giữ nguyên.</span></label>{zeroPrices>0&&<label className="confirmTrialChoice"><input type="checkbox" checked={zero} disabled={busy||disabled} onChange={e=>setZero(e.target.checked)}/><span>Tôi đã kiểm tra {zeroPrices} bộ giá 0 đồng trong bản thử.</span></label>}<button className="salesAction salesActionPrimary confirmTrialSubmit" disabled={busy||disabled||running||!confirmed||(zeroPrices>0&&!zero)} onClick={()=>void confirm()}>{busy?'Đang xác minh…':request.current?'Gửi lại cùng mã thử':'Thử xác nhận trên bản sao'}</button></>}{busy&&<p role="status">Đang tạo bản sao, kiểm tra ảnh và transaction. Không cần bấm lần nữa.</p>}{error&&<p className="notice warning" role="alert">{error}</p>}{request.current&&<div className="confirmTrialActions"><button className="salesAction salesActionSecondary confirmTrialStatus" disabled={busy} onClick={()=>void inspect()}>Kiểm tra trạng thái</button>{result?.canRecover&&<button className="salesAction salesActionMint" disabled={busy} onClick={()=>void recover()}>Phục hồi ảnh bản sao</button>}{result&&result.status!=='RUNNING'&&<button className="salesAction salesActionSecondary" disabled={busy} onClick={fresh}>Tạo lần thử mới</button>}</div>}{result&&<div className="confirmTrialResult" role="status"><b>{done?'✓ Bản sao đã xác nhận bán':restored?'✓ Đã phục hồi bản sao':running?'◷ Lần thử đang chạy':result.status==='PREPARED'?'Chưa commit · có thể phục hồi':'⚠ Bản thử cần kiểm tra'}</b>{done&&<div className="confirmTrialStats"><span>{result.quantity} bộ</span><span>{result.total?.toLocaleString('vi-VN')} đ</span><span>Ảnh gốc {Math.ceil((result.originalBytes||0)/1024)} KB → bản nhẹ {Math.ceil((result.optimizedBytes||0)/1024)} KB</span></div>}<p>{result.message}</p>{done&&<p>Ảnh gốc bản sao được giữ ở staging. Đơn này trong ứng dụng vẫn là nháp, hàng vẫn còn tồn.</p>}</div>}<p className="salesHint">Bản thử phát sinh database/ảnh riêng và được giữ để đối chiếu. Chưa tự dọn file, chưa thuộc backup kho đang dùng. Chưa mở xác nhận bán vận hành.</p></section>
}
