import {useState} from 'react'
import {apiJson} from './uiState'
type Preview={orderId:string;version:number;quantity:number;total:number;zeroPriceCount:number;originalBytes:number;optimizedBytes:number;conflicts:unknown[];items:Array<{imageId:number;productName:string;size:string;originalBytes:number;optimizedBytes:number;width:number;height:number;sourceHash:string}>}
const bytes=(n:number)=>n<1024*1024?(n/1024).toFixed(1)+' KB':(n/1024/1024).toFixed(2)+' MB'
export default function SalesPreview({id,version,disabled}:{id:string;version:number;disabled:boolean}){
 const [preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[index,setIndex]=useState(0),[imageError,setImageError]=useState(false)
 async function prepare(){if(busy)return;setBusy(true);setError('');setPreview(null);try{setPreview(await apiJson('/api/sales/drafts/'+id+'/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version})}));setIndex(0);setImageError(false)}catch(e){setError(e instanceof Error?e.message:'Không tạo được bản xem trước')}finally{setBusy(false)}}
 const item=preview?.items[index]
 return <section className="salesPreview"><div className="salesPreviewHeading"><div><h4>Xem trước ảnh lưu sau bán</h4><p>Thử chất lượng JPEG 1280px · 82%. Ảnh kho giữ nguyên.</p></div><button className="salesAction salesActionMint" disabled={disabled||busy} onClick={()=>void prepare()}>{busy?'Đang kiểm tra và tối ưu…':'Xem trước ảnh nhẹ'}</button></div>{disabled&&<small>Lưu thay đổi và kiểm tra ảnh trước khi xem trước.</small>}{error&&<p role="alert">{error}</p>}{busy&&<p role="status">Đang xử lý lần lượt từng ảnh; chưa bán hay thay đổi kho.</p>}{preview&&item&&<><div className="salesPreviewStats"><span>{preview.quantity} bộ · Giá trị đơn {preview.total.toLocaleString('vi-VN')} đ</span><b>{bytes(preview.originalBytes)} → {bytes(preview.optimizedBytes)}</b><span>{preview.optimizedBytes<preview.originalBytes?'Giảm '+Math.round(100*(1-preview.optimizedBytes/preview.originalBytes))+'% dung lượng':'Bản nhẹ không nhỏ hơn ảnh gốc trong đơn này'}</span></div>{(preview.zeroPriceCount>0||preview.conflicts.length>0)&&<p className="notice warning">{preview.zeroPriceCount>0?preview.zeroPriceCount+' bộ giá 0 đ. ':''}{preview.conflicts.length>0?'Có hàng trong nháp khác. ':''}Cần kiểm tra trước khi chốt bán.</p>}<label className="salesPreviewPicker">Chọn ảnh so sánh<select value={index} onChange={e=>{setIndex(Number(e.target.value));setImageError(false)}}>{preview.items.map((i,n)=><option key={i.imageId} value={n}>{n+1}. {i.productName} · {i.size} · #{i.imageId}</option>)}</select></label><div className="salesPreviewCompare"><figure><img src={'/api/images/'+item.imageId} alt="Ảnh gốc trong kho"/><figcaption>Ảnh gốc · {bytes(item.originalBytes)}</figcaption></figure><figure><img key={item.sourceHash+item.imageId} src={'/api/sales/drafts/'+id+'/preview/'+item.imageId+'?version='+version+'&hash='+item.sourceHash} alt="Bản tối ưu thử nghiệm" onError={()=>setImageError(true)}/><figcaption>Bản nhẹ · {bytes(item.optimizedBytes)} · {item.width} × {item.height}</figcaption></figure></div>{imageError&&<p role="alert">Không tải được bản nhẹ hoặc ảnh đã đổi. Bấm xem trước lại để kiểm tra.</p>}<p className="salesHint">Đây là bản thử để duyệt chất lượng, chưa phải ảnh lưu lịch sử. Nháp vẫn chưa giữ hàng; xem trước không xác nhận bán.</p><button className="salesAction salesActionSecondary" onClick={()=>setPreview(null)}>Thu gọn ảnh so sánh</button></>}</section>
}
