import {useEffect,useRef,useState} from 'react'
import {apiJson} from './uiState'
import './salesConfirmTrial.css'
export default function SalesExecutePanel({id,version,token,zeroPrices,disabled,onBusy,onSold}:{id:string;version:number;token:string;zeroPrices:number;disabled:boolean;onBusy:(b:boolean)=>void;onSold:()=>void}){
 const [agree,setAgree]=useState(false),[zero,setZero]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<any>(null),key=useRef(''),lock=useRef(false),alive=useRef(true),storage='mecacao-sale:'+id
 useEffect(()=>{alive.current=true;try{key.current=localStorage.getItem(storage)||''}catch{}if(key.current)void inspect();return()=>{alive.current=false;onBusy(false)}},[id])
 async function action(fn:()=>Promise<any>){if(lock.current)return;lock.current=true;setBusy(true);onBusy(true);setError('');try{const r=await fn();if(alive.current){setResult(r);if(r.status==='SOLD')onSold()}}catch(e){if(alive.current)setError((e instanceof Error?e.message:'Chưa rõ kết quả')+' · Kiểm tra trạng thái trước khi gửi lại.')}finally{lock.current=false;if(alive.current){setBusy(false);onBusy(false)}}}
 async function inspect(){if(key.current)await action(()=>apiJson('/api/sales/drafts/operations/'+key.current))}
 async function confirm(){if(disabled||!agree||(zeroPrices>0&&!zero))return;if(!key.current){key.current='sale-'+crypto.randomUUID();try{localStorage.setItem(storage,key.current)}catch{}}await action(()=>apiJson('/api/sales/drafts/'+id+'/confirm',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key.current},body:JSON.stringify({version,token,confirmed:true,acknowledgeZeroPrice:zeroPrices>0})}))}
 function fresh(){key.current='';try{localStorage.removeItem(storage)}catch{}setResult(null);setAgree(false);setZero(false)}
 return <section className="confirmTrial saleExecute"><span className="confirmTrialBadge">BÁN TRONG KHO TEST · KHÔNG DÙNG KHO THẬT</span><h4>Xác nhận bán toàn đơn</h4><p>Hàng sẽ ra khỏi tồn sandbox. Lưu lịch sử và ảnh nhẹ; gốc giữ riêng để phục hồi, chưa xóa.</p><label className="confirmTrialChoice"><input className="saleAgree" type="checkbox" checked={agree} disabled={busy||disabled} onChange={e=>setAgree(e.target.checked)}/><span>Tôi đồng ý bán toàn bộ hàng của đơn trong sandbox.</span></label>{zeroPrices>0&&<label className="confirmTrialChoice"><input type="checkbox" checked={zero} disabled={busy||disabled} onChange={e=>setZero(e.target.checked)}/><span>Tôi đã kiểm tra {zeroPrices} bộ giá 0 đồng.</span></label>}<div className="confirmTrialActions"><button className="salesAction salesActionPrimary saleConfirm" disabled={busy||disabled||!agree||(zeroPrices>0&&!zero)||!!result&&result.status!=='NOT_FOUND'} onClick={()=>void confirm()}>{busy?'Đang xác minh…':key.current?'Gửi lại cùng mã bán':'Xác nhận bán sandbox'}</button>{key.current&&<button className="salesAction salesActionSecondary saleStatus" disabled={busy} onClick={()=>void inspect()}>Kiểm tra trạng thái bán</button>}{result?.status==='ROLLED_BACK'&&<button className="salesAction salesActionMint" onClick={fresh}>Tạo mã bán mới sau phục hồi</button>}</div>{error&&<p role="alert" className="notice warning">{error}</p>}{result&&<p role="status">{result.status==='SOLD'?'✓ Đã bán '+result.quantity+' bộ · '+result.total.toLocaleString('vi-VN')+' đ':result.status==='ROLLED_BACK'?'Đã phục hồi ảnh; đơn vẫn nháp':result.status==='NOT_FOUND'?'Chưa có giao dịch; có thể gửi lại cùng mã':'Cần kiểm tra/phục hồi: '+result.status}</p>}</section>
}
export function SalesRecoveryPanel({onRecovered}:{onRecovered:()=>void}){const [busy,setBusy]=useState(false),[message,setMessage]=useState('');async function recover(){if(busy||!window.confirm('Kiểm tra bằng chứng và phục hồi giao dịch bán sandbox? Chưa commit sẽ trả ảnh về kho; đã commit giữ trạng thái SOLD. Không xóa ảnh.'))return;setBusy(true);try{const r=await apiJson('/api/sales/drafts/recover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmed:true})});setMessage(r.status==='CLEAR'?'Không có giao dịch cần phục hồi.':r.status==='SOLD'?'Đã kiểm chứng đơn SOLD; gốc giữ riêng.':'Đã phục hồi; hàng trở lại tồn, đơn vẫn nháp.');onRecovered()}catch(e){setMessage(e instanceof Error?e.message:'Cần kiểm tra thủ công')}finally{setBusy(false)}}return <div className="salesRecovery"><button className="salesAction salesActionMint" disabled={busy} onClick={()=>void recover()}>{busy?'Đang phục hồi…':'Kiểm tra / phục hồi giao dịch bị gián đoạn'}</button>{message&&<p role="status">{message}</p>}</div>}
