import { useEffect,useState } from 'react'
export default function SettingsView(){
 const [threshold,setThreshold]=useState(2),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{fetch('/api/settings').then(r=>r.json()).then(j=>setThreshold(j.lowStockThreshold??2))},[])
 async function save(){const r=await fetch('/api/settings/low-stock-threshold',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({value:threshold})});const j=await r.json();setMsg(r.ok?'Đã lưu ngưỡng tồn thấp.':j.error||'Không thể lưu')}
 async function backupDb(){if(busy)return;setBusy(true);try{const r=await fetch('/api/backup',{method:'POST'});const j=await r.json();setMsg(r.ok?'Đã backup dữ liệu: '+j.backup.file:j.error||'Backup thất bại')}catch{setMsg('Backup thất bại')}finally{setBusy(false)}}
 async function backupImages(){if(busy)return;setBusy(true);try{const r=await fetch('/api/backup/images-optimized',{method:'POST'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Sao lưu ảnh thất bại');const saved=Math.max(0,j.backup.totalOriginalBytes-j.backup.totalBackupBytes);setMsg('Đã sao lưu '+j.backup.optimizedImageCount+' ảnh tối ưu · tiết kiệm khoảng '+Math.round(saved/1024/1024)+' MB'+(j.backup.missingImageCount?' · thiếu '+j.backup.missingImageCount+' ảnh':''))}catch(e){setMsg(e instanceof Error?e.message:'Sao lưu ảnh thất bại')}finally{setBusy(false)}}
 return <section className="panel"><h3>Cài đặt & Backup</h3><div className="formGrid"><label>Ngưỡng tồn thấp<input type="number" min="0" step="1" value={threshold} onChange={e=>setThreshold(Math.max(0,Number(e.target.value)||0))}/></label></div><div className="inventoryActions"><button className="primary" onClick={save}>LƯU CÀI ĐẶT</button><button disabled={busy} onClick={backupDb}>{busy?'ĐANG XỬ LÝ...':'BACKUP NHANH DỮ LIỆU'}</button><button disabled={busy} onClick={backupImages}>SAO LƯU ẢNH TỐI ƯU (THỦ CÔNG)</button></div>{msg&&<p className="notice">{msg}</p>}</section>
}
