import {useEffect,useRef,useState} from 'react'
import FolderPicker from './FolderPicker'
import {apiJson,useBooleanPreference} from './uiState'
import ImageRename from './ImageRename'
type Size={size:string;suggestedSku:string;images:string[];pendingImages:string[];registeredImages:string[];existingVariantId?:number;costPrice?:number;salePrice?:number;selected:boolean;sku:string;cost:number;sale:number}
type Product={name:string;suggestedProductCode:string;existingProductId?:number;sizes:Size[];warnings:string[]}
type Config={rootPath:string;startup:boolean;periodic:boolean;intervalSeconds:number;popup:boolean;autoRename:boolean}
type Result={name:string;status:'SAVED'|'ERROR'|'UNPROCESSED';images:number;sizes:number;message:string}
const defaults:Config={rootPath:'',startup:false,periodic:false,intervalSeconds:300,popup:false,autoRename:false}
export default function WarehouseImport({isDemo,onChanged}:{isDemo:boolean;onChanged:()=>void}){
 const [config,setConfig]=useState(defaults),[picker,setPicker]=useState(false),[snapshot,setSnapshot]=useState<any>(null),[products,setProducts]=useState<Product[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[results,setResults]=useState<Result[]>([]),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[confirm,setConfirm]=useState(false),[previewImage,setPreviewImage]=useState(''),[bulkCost,setBulkCost]=useState(''),[bulkSale,setBulkSale]=useState(''),[progress,setProgress]=useState('')
 const [expanded,setExpanded]=useBooleanPreference('import-expanded',true),lock=useRef(false)
 useEffect(()=>{if(isDemo)return;const c=new AbortController();apiJson('/api/warehouse/settings',{signal:c.signal}).then(async config=>{if(c.signal.aborted)return;setConfig(config);if(config.rootPath){lock.current=true;setBusy(true);const s=await apiJson('/api/store/scan',json({rootPath:config.rootPath}));if(!c.signal.aborted){setConfig(c=>({...c,rootPath:s.rootPath}));setSnapshot(s);setProducts(s.products.map((p:any)=>({...p,sizes:p.sizes.map((v:any)=>({...v,selected:v.pendingImages.length>0,sku:v.suggestedSku,cost:v.costPrice??0,sale:v.salePrice??0}))})))}}}).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted){lock.current=false;setBusy(false)}});return()=>c.abort()},[isDemo])
 const json=(body:unknown)=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})
 async function scan(){if(isDemo||lock.current)return;lock.current=true;setBusy(true);setError('');setConfirm(false)
  try{const s=await apiJson('/api/store/scan',json({rootPath:config.rootPath}));setSnapshot(s);setProducts(s.products.map((p:any)=>({...p,sizes:p.sizes.map((v:any)=>({...v,selected:v.pendingImages.length>0,sku:v.suggestedSku,cost:v.costPrice??0,sale:v.salePrice??0}))})));setMessage('Quét xong; chỉ đọc folder, chưa ghi đăng ký hoặc giao dịch nhập.')}catch(e){setSnapshot(null);setProducts([]);setError(e instanceof Error?e.message:'Quét thất bại')}finally{lock.current=false;setBusy(false)}
 }
 async function saveConfig(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const c=await apiJson('/api/warehouse/settings',{...json(config),method:'PUT'});setConfig(c);setMessage('Đã nhớ kho gốc và cấu hình. Auto rename chỉ áp dụng bản COPY nhập mới.')}catch(e){setError(e instanceof Error?e.message:'Không lưu được')}finally{lock.current=false;setBusy(false)}}
 const visible=products.map((p,i)=>({p,i})).filter(({p})=>(!search||[p.name,p.suggestedProductCode,...p.sizes.flatMap(s=>[s.size,s.sku])].some(x=>x.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'))))&&(filter==='all'||filter==='new'&&!p.existingProductId||filter==='pending'&&p.sizes.some(s=>s.pendingImages.length)||filter==='registered'&&p.sizes.some(s=>s.registeredImages.length)||filter==='warning'&&p.warnings.length))
 const selected=products.map(p=>({...p,sizes:p.sizes.filter(s=>s.selected&&s.images.length)})).filter(p=>p.sizes.length),selectedSizes=selected.flatMap(p=>p.sizes),pending=selectedSizes.reduce((n,s)=>n+s.pendingImages.length,0)
 function patch(i:number,j:number,values:Partial<Size>){setConfirm(false);setProducts(ps=>ps.map((p,x)=>x===i?{...p,sizes:p.sizes.map((s,y)=>y===j?{...s,...values}:s)}:p))}
 function chooseVisible(value:boolean){const indices=new Set(visible.map(x=>x.i));setConfirm(false);setProducts(ps=>ps.map((p,i)=>indices.has(i)?{...p,sizes:p.sizes.map(s=>({...s,selected:value&&s.images.length>0}))}:p))}
 function applyPrices(){const cost=bulkCost===''?null:Number(bulkCost),sale=bulkSale===''?null:Number(bulkSale);if([cost,sale].some(n=>n!==null&&(!Number.isInteger(n)||n<0))){setError('Giá phải là số nguyên không âm');return}setConfirm(false);setProducts(ps=>ps.map(p=>({...p,sizes:p.sizes.map(s=>s.selected?{...s,...(cost===null?{}:{cost}),...(sale===null?{}:{sale})}:s)})));setMessage('Đã áp giá chỉ cho Size được chọn; chưa ghi database.')}
 async function saveBatch(){if(lock.current||!snapshot||!confirm)return;if(snapshot.rootPath!==config.rootPath){setError('Kho gốc đã thay đổi; quét lại trước khi lưu');setConfirm(false);return}if(selectedSizes.some(s=>!Number.isSafeInteger(s.cost)||s.cost<0||!Number.isSafeInteger(s.sale)||s.sale<0)){setError('Giá theo Size phải là số nguyên không âm');setConfirm(false);return}lock.current=true;setBusy(true);setError('');setResults([]);setConfirm(false);const outcomes:Result[]=[]
  try{for(let i=0;i<selected.length;i++){const p=selected[i];setProgress(`${i}/${selected.length} mẫu đã xử lý`);try{
    const data=await apiJson('/api/store/import',json({confirmed:true,product:{rootPath:snapshot.rootPath,name:p.name,productCode:p.suggestedProductCode,variants:p.sizes.map(s=>({size:s.size,sku:s.sku,costPrice:s.cost,salePrice:s.sale,openingStock:s.existingVariantId?0:s.images.length,images:s.images}))}}))
    outcomes.push({name:p.name,status:'SAVED',images:data.registration.images,sizes:data.registration.sizes,message:'Đã đăng ký; ảnh cũ không cộng trùng'})
   }catch(e){outcomes.push({name:p.name,status:'ERROR',images:0,sizes:0,message:e instanceof Error?e.message:'Lỗi lưu'});for(const rest of selected.slice(i+1))outcomes.push({name:rest.name,status:'UNPROCESSED',images:0,sizes:0,message:'Chưa xử lý do lô đã dừng'});break}setResults([...outcomes])}
   setResults(outcomes);setProgress(`${outcomes.filter(o=>o.status==='SAVED').length}/${selected.length} mẫu lưu thành công`);onChanged()
   const s=await apiJson('/api/store/scan',json({rootPath:snapshot.rootPath}));setSnapshot(s);setProducts(s.products.map((p:any)=>({...p,sizes:p.sizes.map((v:any)=>({...v,selected:false,sku:v.suggestedSku,cost:v.costPrice??0,sale:v.salePrice??0}))})))
  }catch(e){setError('Kết quả đã lưu ở bên dưới; lỗi đọc lại kho: '+(e instanceof Error?e.message:''))}finally{lock.current=false;setBusy(false)}
 }
 const metrics=snapshot?[['TỔNG MẪU',snapshot.summary.products,'all'],['TỔNG SIZE/SKU',snapshot.summary.sizes,'all'],['ẢNH PHÁT HIỆN',snapshot.summary.images,'all'],['MẪU ĐÃ ĐĂNG KÝ',snapshot.summary.registeredProducts,'registered'],['SIZE ĐÃ ĐĂNG KÝ',snapshot.summary.registeredSizes,'registered'],['ẢNH ĐÃ ĐĂNG KÝ',snapshot.summary.registeredImages,'registered'],['MẪU MỚI',snapshot.summary.newProducts,'new'],['SIZE MỚI',snapshot.summary.newSizes,'pending'],['ẢNH CHỜ DUYỆT',snapshot.summary.pendingImages,'pending'],['ẢNH ĐĂNG KÝ BỊ THIẾU',snapshot.summary.missingImages,'warning']]:[]
 return <section className="warehouseWorkspace"><div className="dashboardFoldHeader"><div><p className="eyebrow">QUÉT / ĐĂNG KÝ KHO ẢNH</p><h2>Quét kho hiện hữu</h2><p>Chỉ đọc folder. Không ghi database cho đến khi duyệt. Import không phải giao dịch nhập hàng.</p></div><button className="dashboardFoldToggle" aria-expanded={expanded} onClick={()=>setExpanded(v=>!v)}>{expanded?'Thu gọn':'Xem dashboard'}</button></div>{expanded&&<div className="warehouseMetrics">{metrics.length?metrics.map(([label,value,key])=><button key={label} onClick={()=>setFilter(String(key))}><span>{label}</span><strong>{value}</strong></button>):<p>{isDemo?'DEMO: không truy cập ổ đĩa.':'Chọn kho gốc và quét để có số liệu thật.'}</p>}</div>}
 <fieldset disabled={busy||isDemo} className="warehouseConfig"><label>Kho gốc chứa Product → Size → ảnh<div className="row"><input className="grow" value={config.rootPath} onChange={e=>{setConfig({...config,rootPath:e.target.value});setSnapshot(null);setProducts([]);setConfirm(false)}}/><button onClick={()=>setPicker(true)}>CHỌN THƯ MỤC</button><button className="primary" onClick={scan}>QUÉT KHO</button></div></label><div className="watchOptions">{(['startup','periodic','popup','autoRename'] as const).map((key,i)=><label key={key}><input type="checkbox" checked={config[key]} onChange={e=>setConfig({...config,[key]:e.target.checked})}/>{['Quét khi mở backend','Quét định kỳ','Popup thông báo khi không nhập liệu','Tên chuẩn cho ảnh COPY nhập mới'][i]}</label>)}<label>Chu kỳ (giây)<input type="number" min="60" max="86400" value={config.intervalSeconds} onChange={e=>setConfig({...config,intervalSeconds:Number(e.target.value)})}/></label><button onClick={saveConfig}>NHỚ KHO & CẤU HÌNH</button></div></fieldset>
 {picker&&<FolderPicker title="Chọn kho gốc — không chọn riêng Product/Size" onClose={()=>setPicker(false)} onPick={p=>{if(lock.current)return;setConfig({...config,rootPath:p});setSnapshot(null);setProducts([]);setPicker(false)}}/>}
 {busy&&<p role="status">{progress||'Đang đọc/xử lý kho, vui lòng chờ...'}</p>}{error&&<p className="notice warning" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}
 {!!results.length&&<article className="warehouseResults"><h3>Kết quả đăng ký — {progress}</h3><p>Lưu từng Product có transaction; không rollback các Product đã thành công khi mục sau lỗi.</p>{results.map((r,i)=><div key={i} className={'batchOutcome '+r.status}><b>{r.name}</b><span>{r.status==='SAVED'?'ĐÃ LƯU':r.status==='ERROR'?'LỖI':'CHƯA XỬ LÝ'} · +{r.images} ảnh · +{r.sizes} Size</span><small>{r.message}</small></div>)}<div className="row"><button onClick={scan} disabled={busy}>QUÉT LẠI ĐỐI CHIẾU</button><button onClick={()=>window.dispatchEvent(new CustomEvent('mecacao-navigate',{detail:'Tồn kho'}))}>XEM TỒN KHO</button></div></article>}
 {snapshot&&<><p>Quét lúc {new Date(snapshot.scannedAt).toLocaleString('vi-VN')} · {snapshot.rootPath}</p><div className="warehouseToolbar"><input placeholder="Tìm mẫu, mã, Size, SKU..." value={search} onChange={e=>setSearch(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Tất cả</option><option value="new">Mẫu mới</option><option value="pending">Có ảnh chờ duyệt</option><option value="registered">Đã có ảnh đăng ký</option><option value="warning">Cảnh báo</option></select><button disabled={busy} onClick={()=>chooseVisible(true)}>CHỌN KẾT QUẢ LỌC</button><button disabled={busy} onClick={()=>chooseVisible(false)}>BỎ CHỌN</button></div>{snapshot.missing.length>0&&<p className="notice warning">{snapshot.missing.length} ảnh đã đăng ký bị thiếu trên đĩa. Không sửa ledger; kiểm tra trong Tồn kho.</p>}<fieldset disabled={busy} className="warehouseBulk"><label>Giá nhập áp cho mục chọn<input min="0" type="number" value={bulkCost} onChange={e=>setBulkCost(e.target.value)}/></label><label>Giá bán áp cho mục chọn<input min="0" type="number" value={bulkSale} onChange={e=>setBulkSale(e.target.value)}/></label><button onClick={applyPrices}>ÁP GIÁ CHO SIZE ĐÃ CHỌN</button></fieldset>
 <fieldset className="warehouseProducts" disabled={busy}>{visible.map(({p,i})=><article className="warehouseProduct" key={i}><header><h3>{p.name}</h3><span>{p.existingProductId?'ĐÃ CÓ PRODUCT':'MẪU MỚI'}</span><label>Tên mẫu<input disabled title="Tên mẫu bám theo thư mục vật lý; không tự đổi thư mục khi import" value={p.name} onChange={e=>{setConfirm(false);setProducts(ps=>ps.map((v,x)=>x===i?{...v,name:e.target.value}:v))}}/></label><label>Mã Product<input disabled={!!p.existingProductId} value={p.suggestedProductCode} onChange={e=>{setConfirm(false);setProducts(ps=>ps.map((v,x)=>x===i?{...v,suggestedProductCode:e.target.value}:v))}}/></label></header><div className="warehouseTableWrap"><table><thead><tr><th>Chọn</th><th>Ảnh</th><th>Size</th><th>SKU</th><th>Giá nhập (đ)</th><th>Giá bán (đ)</th><th>Phát hiện / Chờ duyệt</th><th>Trạng thái</th></tr></thead><tbody>{p.sizes.map((s,j)=><tr key={j}><td data-label="Chọn"><input aria-label={'Chọn '+p.name+' '+s.size} type="checkbox" disabled={!s.images.length} checked={s.selected} onChange={e=>patch(i,j,{selected:e.target.checked})}/></td><td data-label="Ảnh">{s.images[0]&&<button className="warehouseThumb" onClick={()=>setPreviewImage(s.images[0])}><img loading="lazy" alt={p.name+' '+s.size} src={'/api/warehouse/file?'+new URLSearchParams({rootPath:snapshot.rootPath,path:s.images[0]})}/></button>}</td><td data-label="Size"><input aria-label="Size" disabled title="Size bám theo thư mục vật lý" value={s.size} onChange={e=>patch(i,j,{size:e.target.value})}/></td><td data-label="SKU"><input aria-label="SKU" disabled={!!s.existingVariantId} value={s.sku} onChange={e=>patch(i,j,{sku:e.target.value})}/></td><td data-label="Giá nhập (đ)"><input aria-label="Giá nhập" type="number" min="0" value={s.cost} onChange={e=>patch(i,j,{cost:Number(e.target.value)})}/></td><td data-label="Giá bán (đ)"><input aria-label="Giá bán" type="number" min="0" value={s.sale} onChange={e=>patch(i,j,{sale:Number(e.target.value)})}/></td><td data-label="Ảnh / Chờ duyệt">{s.images.length} ảnh / <b>{s.pendingImages.length} mới</b></td><td data-label="Trạng thái">{s.pendingImages.length?'CHỜ DUYỆT':'ĐÃ ĐĂNG KÝ'}</td></tr>)}</tbody></table></div>{p.warnings.map(w=><p className="warning" key={w}>{w}</p>)}</article>)}</fieldset>{!visible.length&&<p>Không có mẫu khớp bộ lọc; số tổng vẫn nằm trên dashboard.</p>}
 <div className="warehouseConfirm"><b>Đang chọn {selected.length} mẫu · {selectedSizes.length} Size · {pending} ảnh mới</b><p>Ảnh đã đăng ký không cộng trùng. Giá được lưu theo các Size đã chọn.</p>{confirm?<><p>Kiểm tra tên, SKU và giá trước khi xác nhận. Lô dừng ở lỗi đầu tiên.</p><button disabled={busy||!selected.length} className="primary" onClick={saveBatch}>XÁC NHẬN & LƯU HÀNG LOẠT</button><button onClick={()=>setConfirm(false)}>QUAY LẠI DUYỆT</button></>:<button disabled={busy||!selected.length} className="primary" onClick={()=>setConfirm(true)}>DUYỆT LÔ TRƯỚC KHI LƯU</button>}</div></>}
 {!isDemo&&config.rootPath&&<ImageRename rootPath={config.rootPath} onBusy={value=>{lock.current=value;setBusy(value)}} onChanged={()=>{onChanged();setTimeout(()=>void scan(),0)}}/>}
 {previewImage&&<div className="folderOverlay" onClick={()=>setPreviewImage('')}><section className="warehouseImageModal" role="dialog" aria-modal="true" aria-label="Ảnh kho xem lớn"><button onClick={()=>setPreviewImage('')}>ĐÓNG</button><img alt="Ảnh vật lý trong kho" src={'/api/warehouse/file?'+new URLSearchParams({rootPath:snapshot.rootPath,path:previewImage})}/></section></div>}
 </section>
}
