import {useEffect,useRef,useState} from 'react'
import {apiJson} from './uiState'
type Notice={id:string;kind:string;message:string;createdAt:string;state:string}
export default function WarehouseNotifications({isDemo,onReview}:{isDemo:boolean;onReview:()=>void}){
 const [notices,setNotices]=useState<Notice[]>([]),[open,setOpen]=useState(false),[toast,setToast]=useState<Notice|null>(null),[popup,setPopup]=useState<Notice|null>(null),[error,setError]=useState(''),known=useRef(new Set<string>())
 useEffect(()=>{if(isDemo)return;const c=new AbortController();let first=true
  const poll=async()=>{try{const [rows,config]=await Promise.all([apiJson('/api/warehouse/notices',{signal:c.signal}),apiJson('/api/warehouse/settings',{signal:c.signal})]);if(c.signal.aborted)return;const unseen=(rows as Notice[]).filter(n=>n.state==='unseen'&&!known.current.has(n.id));for(const n of rows)known.current.add(n.id);setNotices(rows);setError('');if(unseen.length){setToast(unseen[0]);const target=document.activeElement?.tagName;if(config.popup&&!['INPUT','TEXTAREA','SELECT'].includes(target??'')&&!document.querySelector('[role=dialog],fieldset:disabled'))setPopup(unseen[0])}first=false}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Không đọc được thông báo kho')}}
  void poll();const timer=setInterval(poll,15000);return()=>{c.abort();clearInterval(timer)}
 },[isDemo])
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(null),8000);return()=>clearTimeout(timer)},[toast])
 async function mark(id:string,state:string){try{setNotices(await apiJson('/api/warehouse/notices/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({state})}));setToast(null);setPopup(null)}catch(e){setError(e instanceof Error?e.message:'Không lưu được trạng thái')}}
 function review(n:Notice){void mark(n.id,'seen');setOpen(false);onReview()}
 if(isDemo)return null
 return <div className="warehouseNotifications"><button aria-label="Thông báo kho" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg><span>{notices.filter(n=>n.state==='unseen').length}</span></button>{toast&&!open&&<aside className="warehouseToast" role="status"><b>Thay đổi kho ảnh</b><p>{toast.message}</p><button onClick={()=>review(toast)}>XEM & DUYỆT</button><button onClick={()=>setToast(null)}>ẨN</button></aside>}{open&&<section className="warehouseNoticePanel" aria-label="Danh sách thông báo kho"><h3>Thông báo kho</h3>{error&&<p role="alert">{error}</p>}{!notices.length&&<p>Chưa có thông báo. Bật quét tự động trong Import kho.</p>}{notices.map(n=><article key={n.id}><b>{n.state==='unseen'?'CHƯA XEM':n.state==='seen'?'ĐÃ XEM':'ĐÃ XỬ LÝ'}</b><p>{n.message}</p><small>{n.createdAt}</small><div className="row"><button onClick={()=>review(n)}>XEM & DUYỆT</button>{n.state!=='resolved'&&<button onClick={()=>mark(n.id,'resolved')}>ĐÃ XỬ LÝ</button>}</div></article>)}</section>}{popup&&<div className="folderOverlay"><section className="folderModal" role="dialog" aria-modal="true" aria-label="Kho ảnh có thay đổi"><h3>Kho ảnh có thay đổi</h3><p>{popup.message}</p><button className="primary" onClick={()=>review(popup)}>XEM & DUYỆT</button><button onClick={()=>setPopup(null)}>ĐỂ SAU</button></section></div>}</div>
}
