import {validateStocktakes} from './stocktake.js'
import {validateFinance} from './orderFinance.js'
import fs from 'node:fs'
import path from 'node:path'
import {randomUUID} from 'node:crypto'
import {DatabaseSync} from 'node:sqlite'
import {assertDatabaseIntegrity,readSchemaVersion} from './schema.js'
import {SALES_AREA,contained,digest,exactFile,writeDurable,syncDirectory,salesActivity,salesExecutionService} from './salesExecution.js'
import {archiveSnapshot} from './archiveSnapshot.js'
import {ARCHIVE_FOLDER} from './salesArchive.js'

type File={relative:string;backup_path:string;sha256:string;size:number}
type Manifest={version:3|4;mode:'lossless-recovery';database:'shop.db';database_sha256:string;sourceRoot:string;records:Array<{id:number;canonical:string;sold:boolean}>;files:File[]}
function relative(root:string,p:string){const r=path.relative(root,path.resolve(p));if(!contained(root,path.resolve(p))||r.split(path.sep).some(n=>!n||n==='.'||n==='..'))throw Error('File không thuộc sandbox');return r}
function resolve(root:string,r:string){if(typeof r!=='string'||path.isAbsolute(r)||relative(root,path.resolve(root,r))!==r)throw Error('Đường dẫn bundle không hợp lệ');return path.resolve(root,r)}
function copy(source:string,target:string,sha:string){fs.mkdirSync(path.dirname(target),{recursive:true});if(fs.realpathSync(path.dirname(target))!==path.dirname(target))throw Error('Copy đi qua liên kết');const b=exactFile(source,sha);writeDurable(target,b);exactFile(target,sha);exactFile(source,sha)}
function validate(db:DatabaseSync,m:Manifest,file:(r:string)=>Buffer){
 assertDatabaseIntegrity(db);validateFinance(db);validateStocktakes(db);if(readSchemaVersion(db)!==130)throw Error('Backup sale không phải schema130')
 if((db.prepare("SELECT value FROM app_metadata WHERE key='warehouse_layout'").get()?.value==='DIRECT')!==(m.version===4))throw Error('Manifest không khớp kiểu kho DIRECT/sandbox')
 const records=db.prepare('SELECT id,file_path FROM product_images ORDER BY id').all(),seen=new Set<number>(),names=new Set<string>(),index=new Map(m.files.map(f=>[f.relative,f]))
 if(records.length!==m.records.length)throw Error('Manifest không đủ image IDs')
 const canonicalOK=(r:string)=>r.split(path.sep).length===(m.version===4?3:4)&&(m.version===4?!r.split(path.sep).some(p=>p.startsWith('.mecacao-')):r.split(path.sep)[0]==='warehouse')
 for(const r of m.records){if(!Number.isSafeInteger(r.id)||seen.has(r.id)||names.has(r.canonical.toLowerCase())||!records.some(i=>i.id===r.id&&relative(m.sourceRoot,String(i.file_path))===r.canonical)||!canonicalOK(r.canonical))throw Error('Canonical mapping không đúng Product/Size/ảnh');seen.add(r.id);names.add(r.canonical.toLowerCase());const u=db.prepare('SELECT 1 FROM sales_units WHERE image_id=?').get(r.id);if(!!u!==r.sold||(!r.sold&&!index.has(r.canonical))||(r.sold&&index.has(r.canonical)))throw Error('Vai trò AVAILABLE/SOLD không đúng')}
 for(const o of db.prepare('SELECT * FROM sales_operations').all()){
  if(o.status==='PREPARED'||digest(String(o.payload))!==o.payload_hash)throw Error('Backup còn recovery hoặc payload sai');const p=JSON.parse(String(o.payload));if(p.id!==o.id||p.inputHash!==o.input_hash||p.format!==1||!Array.isArray(p.units)||!p.units.length||p.units.length>100)throw Error('Payload bán không hợp lệ');if(digest(file(path.join(SALES_AREA,String(o.id),'plan.json')))!==o.payload_hash)throw Error('File journal sai');const c=db.prepare('SELECT * FROM sales_confirmations WHERE operation_id=?').get(o.id),units=db.prepare('SELECT * FROM sales_units WHERE order_id=?').all(p.orderId),ledger=db.prepare('SELECT * FROM sales_ledger WHERE order_id=?').all(p.orderId)
  if(o.status==='ROLLED_BACK'){if(c)throw Error('Rollback có bằng chứng bán');for(const u of p.units)if((!db.prepare('SELECT 1 FROM sales_units WHERE image_id=?').get(u.imageId)&&digest(file(u.canonical))!==u.sourceHash)||index.has(u.staged))throw Error('Rollback ảnh không đủ');continue}
  if(o.status!=='SOLD'||!c||c.order_id!==p.orderId||c.version!==p.version||c.subtotal!==p.subtotal||c.discount!==p.discount||c.total!==p.total||c.note!==p.note||units.length!==p.units.length||ledger.length!==units.length)throw Error('Sale snapshot sai')
  for(const u of p.units){const r=units.find(r=>r.image_id===u.imageId),l=ledger.find(r=>r.image_id===u.imageId);if(!r||!l||r.snapshot!==JSON.stringify(u.snapshot)||r.source_hash!==u.sourceHash||r.archive_path!==u.archive||r.archive_hash!==u.archiveHash||r.variant_id!==u.snapshot.variant_id||l.variant_id!==r.variant_id||l.unit_cost!==u.snapshot.unit_cost||l.quantity!==1||l.transaction_type!=='SALE'||!canonicalOK(u.canonical)||!u.staged.startsWith(path.join(SALES_AREA,p.id,'staged')+path.sep)||!u.archive.startsWith(path.join(SALES_AREA,p.id,'archive')+path.sep)||digest(file(u.staged))!==u.sourceHash||digest(file(u.archive))!==u.archiveHash)throw Error('Backup ảnh SOLD/ledger sai')}
 }
 if(Number(db.prepare('SELECT COUNT(*) n FROM sales_units').get()!.n)!==m.records.filter(r=>r.sold).length||Number(db.prepare('SELECT COUNT(*) n FROM sales_ledger').get()!.n)!==m.records.filter(r=>r.sold).length)throw Error('Backup claims/ledger không đủ')
}
export function createSalesBackup(db:DatabaseSync,dbPath:string,rootInput:string,onProgress?:(p:any)=>void){
 const root=fs.realpathSync(rootInput);if(salesActivity.busy||fs.existsSync(path.join(root,SALES_AREA+'-pending.json')))throw Error('Giao dịch bán chưa rõ; dừng backup đầy đủ')
 const service=salesExecutionService(db,root);if(service.pending())throw Error('Giao dịch cần phục hồi')
 const records=(db.prepare('SELECT id,file_path FROM product_images ORDER BY id').all()).map(r=>({id:Number(r.id),canonical:relative(root,String(r.file_path)),sold:!!db.prepare('SELECT 1 FROM sales_units WHERE image_id=?').get(r.id)})),sources:string[]=[]
 for(const r of records)if(!r.sold)sources.push(resolve(root,r.canonical));else if(fs.existsSync(resolve(root,r.canonical)))throw Error('Canonical đã bán xuất hiện lại; kiểm tra trước backup')
 function walk(dir:string){if(!fs.existsSync(dir))return;if(fs.realpathSync(dir)!==dir||!fs.lstatSync(dir).isDirectory())throw Error('Sales folder không an toàn');for(const n of fs.readdirSync(dir)){const p=path.join(dir,n);if(fs.lstatSync(p).isDirectory())walk(p);else{exactFile(p);sources.push(p)}}}
 walk(path.join(root,SALES_AREA));for(const a of archiveSnapshot(root))sources.push(a.source)
 const direct=db.prepare("SELECT value FROM app_metadata WHERE key='warehouse_layout'").get()?.value==='DIRECT'
 const files=sources.map(p=>({relative:relative(root,p),backup_path:path.join('files',relative(root,p)),sha256:digest(exactFile(p)),size:fs.statSync(p).size})),m:Manifest={version:direct?4:3,mode:'lossless-recovery',database:'shop.db',database_sha256:'',sourceRoot:root,records,files}
 validate(db,m,r=>exactFile(resolve(root,r)))
 const parent=path.join(path.dirname(dbPath),'backups');fs.mkdirSync(parent,{recursive:true});if(fs.realpathSync(parent)!==parent)throw Error('Backup parent không an toàn');const dir=path.join(parent,'sales-'+randomUUID());fs.mkdirSync(dir)
 const snapshot=path.join(dir,'shop.db');db.exec("VACUUM INTO '"+snapshot.replace(/'/g,"''")+"'");m.database_sha256=digest(exactFile(snapshot));for(let i=0;i<files.length;i++){copy(sources[i],path.join(dir,files[i].backup_path),files[i].sha256);onProgress?.({phase:'BACKUP_COPY',completed:i+1,total:files.length,current:files[i].relative})}
 onProgress?.({phase:'BACKUP_VERIFY',completed:files.length,total:files.length})
 writeDurable(path.join(dir,'lossless-manifest.json'),JSON.stringify(m));const verified=verifySalesBackup(dir)
 return {directory:dir,database:snapshot,mode:'lossless-recovery',imageCount:records.length,soldImageCount:records.filter(r=>r.sold).length,archiveFileCount:files.filter(f=>f.relative.startsWith(SALES_AREA+path.sep)).length,totalBytes:files.reduce((n,f)=>n+f.size,0),manifest:'lossless-manifest.json',verified}
}
export function verifySalesBackup(input:string){const dir=fs.realpathSync(input),m=JSON.parse(exactFile(path.join(dir,'lossless-manifest.json')).toString()) as Manifest
 if(![3,4].includes(m.version)||m.mode!=='lossless-recovery'||m.database!=='shop.db'||typeof m.sourceRoot!=='string'||!path.isAbsolute(m.sourceRoot)||!Array.isArray(m.records)||!Array.isArray(m.files)||digest(exactFile(path.join(dir,'shop.db')))!==m.database_sha256)throw Error('Manifest sale không hợp lệ')
 const index=new Map<string,File>(),paths=new Set<string>();for(const f of m.files){const p=resolve(dir,f.backup_path);if(index.has(f.relative)||paths.has(p.toLowerCase())||!Number.isSafeInteger(f.size)||f.size<0||! /^[a-f0-9]{64}$/.test(f.sha256)||exactFile(p,f.sha256).length!==f.size)throw Error('File sale backup thiếu/trùng/sai');resolve(m.sourceRoot,f.relative);index.set(f.relative,f);paths.add(p.toLowerCase())}
 const snapshot=new DatabaseSync(path.join(dir,'shop.db'),{readOnly:true});try{validate(snapshot,m,r=>{const f=index.get(r);if(!f)throw Error('Backup thiếu file '+r);return exactFile(resolve(dir,f.backup_path),f.sha256)})}finally{snapshot.close()}
 return {ok:true,dbVerified:true,imagesVerified:m.records.length,archiveFilesVerified:m.files.filter(f=>f.relative.startsWith(SALES_AREA+path.sep)).length,soldImagesVerified:m.records.filter(r=>r.sold).length}
}
export function restoreSalesBackup(input:string,targetInput:string,oldWarehouseInput:string,checkpoint:(point:string)=>void=()=>{}){
 const bundle=fs.realpathSync(input),verified=verifySalesBackup(bundle),m=JSON.parse(exactFile(path.join(bundle,'lossless-manifest.json')).toString()) as Manifest,target=path.resolve(targetInput),old=path.resolve(oldWarehouseInput)
 if(old!==(m.version===4?m.sourceRoot:path.join(m.sourceRoot,'warehouse'))||fs.realpathSync(path.dirname(target))!==path.dirname(target)||fs.existsSync(target)||target===m.sourceRoot||contained(old,target)||contained(target,old)||contained(path.join(m.sourceRoot,SALES_AREA),target)||contained(path.join(m.sourceRoot,'database'),target)||contained(target,m.sourceRoot)||target===bundle||contained(bundle,target))throw Error('Restore bán chỉ sang thư mục mới riêng, đúng kho gốc')
 fs.mkdirSync(target);writeDurable(path.join(target,'restore-plan.json'),JSON.stringify({schema:130,bundle,status:'COPYING'}));checkpoint('plan')
 const restoredRoot=m.version===4?path.join(target,'warehouse'):target
 for(let n=0;n<m.files.length;n++){const f=m.files[n];copy(resolve(bundle,f.backup_path),resolve(restoredRoot,f.relative),f.sha256);checkpoint('file:'+n)}
 const database=path.join(target,'database','shop-restored.db'),warehouse=path.join(target,'warehouse');fs.mkdirSync(warehouse,{recursive:true});copy(path.join(bundle,'shop.db'),database,m.database_sha256);checkpoint('database-copy')
 const counts:Record<string,number>={}
 const restored=new DatabaseSync(database);try{restored.exec('PRAGMA foreign_keys=ON;PRAGMA synchronous=FULL;BEGIN IMMEDIATE');try{for(const r of m.records)restored.prepare('UPDATE product_images SET file_path=? WHERE id=?').run(resolve(restoredRoot,r.canonical),r.id);const row=restored.prepare("SELECT value FROM app_settings WHERE key='warehouse-watch'").get();if(row){const c=JSON.parse(String(row.value));restored.prepare("UPDATE app_settings SET value=? WHERE key='warehouse-watch'").run(JSON.stringify({...c,rootPath:warehouse,startup:false,periodic:false,autoRename:false}))}restored.prepare("DELETE FROM app_settings WHERE key IN ('warehouse-last-scan','warehouse-notices')").run();assertDatabaseIntegrity(restored);checkpoint('before-db-commit');restored.exec('COMMIT')}catch(e){restored.exec('ROLLBACK');throw e};checkpoint('db-commit');validate(restored,{...m,sourceRoot:restoredRoot},r=>exactFile(resolve(restoredRoot,r)));for(const r of m.records)if(r.sold&&fs.existsSync(resolve(restoredRoot,r.canonical)))throw Error('Restore đã bán thành tồn');for(const table of ['products','product_variants','product_images','inventory_transactions','sales_orders','sales_order_images','sales_operations','sales_confirmations','sales_units','sales_ledger',...['shop_customers','order_contacts','order_finance','finance_entries','aftercare_cases','stocktake_sessions','stocktake_rows'].filter(t=>restored.prepare("SELECT 1 FROM sqlite_master WHERE name=?").get(t))])counts[table]=Number(restored.prepare('SELECT COUNT(*) n FROM '+table).get()!.n);}finally{restored.close()}
 verifySalesBackup(bundle);writeDurable(path.join(target,'restore-ready.json'),JSON.stringify({format:1,status:'READY',schema:130,backupVersion:m.version,database,warehouse,counts,imagesVerified:verified.imagesVerified,archiveFilesVerified:verified.archiveFilesVerified,completedAt:new Date().toISOString()}));checkpoint('ready');return {status:'READY',activated:false,targetRoot:target,database,warehouse,schema:130,backupVersion:m.version,counts,...verified}
}
