import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import assert from 'node:assert/strict'
import {spawnSync,spawn} from 'node:child_process'
import {fileURLToPath} from 'node:url'
import sharp from 'sharp'
import {DatabaseSync} from 'node:sqlite'
import {bootstrapSalesDrafts} from './salesSchema.js'
import {bootstrapV100} from './schema.js'
import {bootstrapSalesExecution,salesExecutionService,SALES_AREA,digest,salesActivity} from './salesExecution.js'
import {salesDraftService} from './salesDrafts.js'
import {salesPreflightService} from './salesPreflight.js'
import {createSalesBackup,verifySalesBackup,restoreSalesBackup} from './salesBackup.js'
import {rejectSoldSource} from './soldSource.js'
let n=0;function eq(a:unknown,b:unknown){assert.deepEqual(a,b);n++}function ok(a:unknown){assert.ok(a);n++}function fails(fn:()=>unknown){assert.throws(fn);n++}async function rejects(fn:()=>Promise<unknown>){await assert.rejects(fn);n++}
const base=fs.mkdtempSync(path.join(os.tmpdir(),'mecacao-sale-'))
async function fixture(name:string){const root=path.join(base,name);fs.mkdirSync(path.join(root,'database'),{recursive:true});const file=path.join(root,'database','shop-sale.db'),db=new DatabaseSync(file);bootstrapSalesDrafts(db);db.exec("INSERT INTO products(id,product_code,name) VALUES(1,'P1','Bộ test');INSERT INTO product_variants(id,product_id,sku,size,cost_price,sale_price) VALUES(1,1,'P1-S1','Size 1',10000,50000);INSERT INTO inventory_transactions(variant_id,transaction_type,quantity) VALUES(1,'OPENING',8)");const photos=[];for(let i=1;i<=3;i++){const p=path.join(root,'warehouse','Bộ test','Size 1',i+'.png');fs.mkdirSync(path.dirname(p),{recursive:true});await sharp({create:{width:150,height:170,channels:3,background:{r:30*i,g:70,b:100}}}).png().toFile(p);db.prepare('INSERT INTO product_images(id,product_id,variant_id,file_path) VALUES(?,1,1,?)').run(i,p);photos.push({p,hash:digest(fs.readFileSync(p))})}const draft=salesDraftService(db,root).create({items:[{imageId:1,unitPrice:50000},{imageId:2,unitPrice:50000}],discount:1000,note:'Test'},'create-order-key-0001');fs.writeFileSync(path.join(root,'fixture.json'),JSON.stringify({id:draft.id}));bootstrapSalesExecution(db,root);const input={version:1,token:(await salesPreflightService(db,root).check(draft.id,1)).token,confirmed:true,acknowledgeZeroPrice:false};return {root,file,db,draft,input,photos,service:salesExecutionService(db,root)}}
if(process.argv[2]==='restore-worker'){restoreSalesBackup(process.argv[3],process.argv[4],process.argv[5],p=>{if(p===process.argv[6])process.exit(78)});process.exit(0)}
if(process.argv[2]==='worker'){const root=process.argv[3],point=process.argv[4],db=new DatabaseSync(path.join(root,'database','shop-sale.db')),id=JSON.parse(fs.readFileSync(path.join(root,'fixture.json'),'utf8')).id,token=(await salesPreflightService(db,root).check(id,1)).token;await salesExecutionService(db,root).confirm(id,{version:1,token,confirmed:true,acknowledgeZeroPrice:false},'sale-hard-exit-key-0001',p=>{if(p===point)process.exit(78)});db.close();process.exit(0)}
try{
 const f=await fixture('happy'),d=salesDraftService(f.db,f.root);eq(d.get(f.draft.id).status,'DRAFT');ok(fs.readdirSync(path.dirname(f.file)).some(p=>p.includes('pre-v130')))
 await rejects(()=>f.service.confirm(f.draft.id,{...f.input,confirmed:false},'sale-request-key-0001'));await rejects(()=>f.service.confirm(f.draft.id,{...f.input,token:'0'.repeat(64)},'sale-request-key-0001'));eq(f.service.pending(),false)
 f.db.exec('UPDATE product_variants SET cost_price=12000 WHERE id=1');
 const result=await f.service.confirm(f.draft.id,f.input,'sale-request-key-0001');eq(result.status,'SOLD');eq(result.quantity,2);eq(result.total,99000);eq(d.get(f.draft.id).status,'SOLD');eq(d.list('DRAFT').length,0);eq(d.list('SOLD').length,1);eq(Number(f.db.prepare('SELECT stock FROM inventory_stock WHERE variant_id=1').get()!.stock),6);eq(Number(f.db.prepare('SELECT SUM(quantity) n FROM sales_ledger').get()!.n),2);eq(Number(f.db.prepare('SELECT quantity FROM inventory_transactions').get()!.quantity),8)
 eq(fs.existsSync(f.photos[0].p),false);eq(fs.existsSync(f.photos[1].p),false);eq(digest(fs.readFileSync(f.photos[2].p)),f.photos[2].hash);eq((await f.service.confirm(f.draft.id,f.input,'sale-request-key-0001')).operationId,result.operationId);await rejects(()=>f.service.confirm(f.draft.id,{...f.input,version:2},'sale-request-key-0001'));fails(()=>d.update(f.draft.id,{version:1,items:[{imageId:3,unitPrice:4}],discount:0,note:''}));fails(()=>d.cancel(f.draft.id,1));fails(()=>d.create({items:[{imageId:1,unitPrice:4}],discount:0,note:''},'create-order-key-0002'));fails(()=>rejectSoldSource(f.db,f.photos[0].hash));fails(()=>f.db.prepare('UPDATE sales_orders SET discount=0 WHERE id=?').run(f.draft.id));fails(()=>f.db.exec('DELETE FROM sales_ledger'));eq((await f.service.image(f.draft.id,1)).slice(0,2),Buffer.from([255,216]));eq(f.service.history(f.draft.id).quantity,2);eq(f.service.history(f.draft.id).items[0].unit_cost,12000)
 const backup=createSalesBackup(f.db,f.file,f.root);eq(backup.verified.soldImagesVerified,2);eq(backup.imageCount,3);const target=path.join(base,'restored'),restored=restoreSalesBackup(backup.directory,target,path.join(f.root,'warehouse'));eq(restored.schema,130);const copy=new DatabaseSync(restored.database),copyService=salesExecutionService(copy,target);eq(salesDraftService(copy,target).get(f.draft.id).status,'SOLD');eq((await copyService.status('sale-request-key-0001')).status,'SOLD');eq(fs.existsSync(path.join(target,'warehouse','Bộ test','Size 1','1.png')),false);eq(digest(fs.readFileSync(path.join(target,'warehouse','Bộ test','Size 1','3.png'))),f.photos[2].hash);ok((await copyService.image(f.draft.id,1)).length>0);const backup2=createSalesBackup(copy,restored.database,target);eq(verifySalesBackup(backup2.directory).soldImagesVerified,2);copy.close();fails(()=>restoreSalesBackup(backup.directory,target,path.join(f.root,'warehouse')))
 for(const point of ['plan','file:0','database-copy','before-db-commit','db-commit','ready']){const target=path.join(base,'restore-exit-'+point.replace(':','-')),r=spawnSync(process.execPath,['--import','tsx',fileURLToPath(import.meta.url),'restore-worker',backup.directory,target,path.join(f.root,'warehouse'),point],{timeout:30000,encoding:'utf8'});eq(r.status,78);eq(fs.existsSync(path.join(target,'restore-ready.json')),point==='ready');eq(verifySalesBackup(backup.directory).ok,true)}
 const archive=f.db.prepare('SELECT archive_path FROM sales_units WHERE image_id=1').get()!;const a=path.join(f.root,String(archive.archive_path)),bytes=fs.readFileSync(a);fs.writeFileSync(a,'corrupt');eq((await f.service.status('sale-request-key-0001')).status,'RECOVERY_REQUIRED');fails(()=>createSalesBackup(f.db,f.file,f.root));fs.writeFileSync(a,bytes)
 // A sold file reappearing physically must never count as sellable or be accepted by backup.
 fs.copyFileSync(f.photos[2].p,f.photos[0].p);eq(d.get(f.draft.id).items[0].unavailable,'Bộ hàng đã bán');fails(()=>createSalesBackup(f.db,f.file,f.root));fs.unlinkSync(f.photos[0].p);f.db.close()
 for(const point of ['lock','archive:0','archive:1','prepared-db','journal','linked:0','staged:0','linked:1','staged:1','sale-row','unit:0','unit:1','before-commit','after-commit','released']){
  const x=await fixture('crash-'+point.replace(':','-'));x.db.close();const r=spawnSync(process.execPath,['--import','tsx',fileURLToPath(import.meta.url),'worker',x.root,point],{timeout:30000,encoding:'utf8'});eq(r.status,78);const db=new DatabaseSync(x.file),s=salesExecutionService(db,x.root);if(point==='prepared-db'){await rejects(()=>s.recover());eq(s.pending(),true)}else{const state=await s.recover();const sold=['after-commit','released'].includes(point);eq(state.status,sold?(point==='released'?'CLEAR':'SOLD'):'ROLLED_BACK');eq(s.pending(),false);eq(salesDraftService(db,x.root).get(x.draft.id).status,sold?'SOLD':'DRAFT');eq(Number(db.prepare('SELECT COUNT(*) n FROM sales_ledger').get()!.n),sold?2:0);for(let i=0;i<2;i++)eq(fs.existsSync(x.photos[i].p),!sold);if(sold)eq((await s.status('sale-hard-exit-key-0001')).status,'SOLD');else{for(const photo of x.photos)eq(digest(fs.readFileSync(photo.p)),photo.hash);if(point.startsWith('staged')||point==='before-commit'){const input={...x.input,token:(await salesPreflightService(db,x.root).check(x.draft.id,1)).token};eq((await s.confirm(x.draft.id,input,'sale-retry-new-key-0001')).status,'SOLD');ok(createSalesBackup(db,x.file,x.root).verified.ok)}}}db.close()
 }
 const collision=await fixture('collision');await rejects(()=>collision.service.confirm(collision.draft.id,collision.input,'sale-collision-key-001',p=>{if(p==='staged:1')throw Error('fault')}));fs.copyFileSync(collision.photos[2].p,collision.photos[0].p);await rejects(()=>collision.service.recover());eq(digest(fs.readFileSync(collision.photos[0].p)),collision.photos[2].hash);eq(fs.existsSync(collision.photos[1].p),false);eq(collision.service.pending(),true);collision.db.close()
 const compete=await fixture('two-process');compete.db.close();const execute=()=>new Promise<number|null>(resolve=>{const c=spawn(process.execPath,['--import','tsx',fileURLToPath(import.meta.url),'worker',compete.root,'never'],{stdio:'ignore'});c.on('exit',resolve)}),codes=await Promise.all([execute(),execute()]);ok(codes.includes(0));const competeDb=new DatabaseSync(compete.file);eq(Number(competeDb.prepare('SELECT COUNT(*) n FROM sales_confirmations').get()!.n),1);eq(Number(competeDb.prepare('SELECT COUNT(*) n FROM sales_units').get()!.n),2);eq(Number(competeDb.prepare('SELECT COUNT(*) n FROM sales_ledger').get()!.n),2);competeDb.close()
 const concurrent=await fixture('concurrent');salesActivity.readers=1;await rejects(()=>concurrent.service.confirm(concurrent.draft.id,concurrent.input,'sale-concurrent-key-0001'));salesActivity.readers=0;let second:Promise<unknown>|undefined;await concurrent.service.confirm(concurrent.draft.id,concurrent.input,'sale-concurrent-key-0001',p=>{if(p==='archive:0')second=concurrent.service.confirm(concurrent.draft.id,concurrent.input,'sale-concurrent-key-0002').then(()=>{throw Error('Second unexpectedly won')},()=>{n++})});await second;concurrent.db.close()
 console.log(`V2_SALES_EXECUTION PASS: ${n} assertions; atomic whole-order sale, retained originals, immutable history, ledger/physical separation, idempotency, fifteen sale/six restore hard exits, two-process contention, fail-closed recovery, role-aware backup/portable restore and conflict guards`)
}finally{salesActivity.readers=0;fs.rmSync(base,{recursive:true,force:true})}
